In [ ]:
pip install git+https://github.com/tweepy/tweepy.git

In [ ]:
pip install geopy

In [ ]:
pip install textblob

In [ ]:
pip install -U pymongo

In [1]:
import tweepy
import pandas as pd
from pymongo import MongoClient, ASCENDING, TEXT
import pymongo
import configparser
import datetime
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="geoapiExercises")
from textblob import TextBlob

In [2]:
# read configs
config = configparser.ConfigParser()
config.read('config.ini')

consumer_key = config['twitter']['api_key']
consumer_secret = config['twitter']['api_key_secret']

access_token = config['twitter']['access_token']
access_secret = config['twitter']['access_token_secret']
# bearer_token = config['twitter']['bearer_token']

In [3]:
#Connect tomongoDb Cluster
client = MongoClient('mongodb+srv://Twitter_analysis:Twitter_analysis@cluster1.owjc6au.mongodb.net/?retryWrites=true&w=majority')
db=client.twitter

In [4]:
movie_TV=db.movie_TV
Temp_collection=db.Temp_collection
# movie_TV_1=db.movie_TV_1
# movie_vt.create_index([('id',ASCENDING)],unique=True)
# temp.create_index([('id',ASCENDING)],unique=True)

In [ ]:
movie_TV.index_information()  # return the indexes

In [ ]:
Temp_collection.index_information()  # return the indexes

{'_id_': {'v': 2, 'key': [('_id', 1)]}}

In [ ]:
# authentication
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)
api = tweepy.API(auth)

### WE MANUALLY TOOK MORE COORDINATES FROM ALL OVER THE WORLD

In [ ]:
Andhra_Pradesh = ["19.04815133576942,84.65571208142063,15mi","18.772602895764383,84.45942173448992,15mi","18.62265872228743, 84.23780360085843,15mi","18.514616914212585, 84.06367506729084,15mi","18.388481877760462, 83.9085423737488,15mi","18.45156097728103, 83.55711933327605,15mi","18.862505493914714, 83.39248871972121,15mi","18.610657458859137, 83.32283730629419,15mi","18.166019527069853, 83.37665885303326,15mi","17.985436181404445, 83.41465053308437,15mi","18.430537181041178, 82.8954309057192,15mi","18.126908912390842, 82.68331069210049,15mi","18.502608039913813, 83.09172124471999,15mi","17.780551531937242, 83.2215261429705,15mi","17.994469739798102, 82.90809478254884,15mi","18.370455018042264, 82.42370086189719,15mi","17.855904232537497, 82.51234811534977,15mi","17.599575554337463, 82.62315718216551,15mi","17.421438836231445, 82.5471738220633,15mi","17.258245940423205, 82.33188763510701,15mi","17.119115724979288, 82.30972582174384,15mi","17.662937876529224, 81.72718672762683,15mi","17.94628534073806, 82.05644795473646,15mi","16.93748513010875, 82.21791258636293,15mi","16.676842303039496, 82.19891674633736,15mi","17.046484646495, 81.81266799915107,15mi","16.934456462149623, 81.8095020258135,15mi","16.49175183247339, 81.99946042606904,15mi","16.843573790614524, 81.50873455874218,15mi","16.585836456188215, 81.52773039876774,15mi","16.406732832867835, 81.78734021245033,15mi","16.403695751696763, 81.45491301200312,15mi","16.773867494207487, 81.06866426481683,15mi","16.236583509203353, 81.10982190128827,15mi","16.546387191081546, 80.63492590064939,15mi","15.95977737207964, 80.99901283447254,15mi","16.20922431104127, 80.6729175807005,15mi","16.330791594470476, 80.43230360704347,15mi","16.99502053950628, 80.73307105362899,15mi","16.734456956135105, 80.4291376132201,15mi","16.62527761417115, 80.03655691935863,15mi","16.552456825308845, 79.71995955031107,15mi","16.339906094319247, 79.47617960331645,15mi","16.15145352940219, 79.20707186962109,15mi","16.04498954963093, 78.95695997595128,15mi","15.673443695042549, 79.27672328304811,15mi","15.847119962904571, 79.81810472377644,15mi","15.398917569395293, 80.03022492497153,15mi","15.21569826568777, 79.90358599146784,15mi","15.347021727374855, 79.51733724428153,15mi","15.667347084974, 79.26405937727414,15mi","15.901934136863, 78.6466945764436,15mi","15.783151248823268, 78.2382839800772,15mi","15.50877187112463, 78.47889795373422,15mi","15.761823853151816, 77.62725109446627,15mi","15.4569034798499, 77.84570325476017,15mi","15.65820184150167, 77.26949610731833,15mi","15.203477949107342, 77.32964960073258,15mi","14.769201838451751, 77.56076565939915,15mi","14.735524145714184, 77.74755808631711,15mi","14.447521693232387, 77.71906432627878,15mi","14.214395290633915, 77.77921781969305,15mi","14.128445793913645, 78.13064086016581,15mi","14.110023814541428, 78.75117163433394,15mi","14.171424611854722, 79.19757387493449,15mi","14.453653317578343, 79.47301355530503,15mi","15.04454962887762, 79.16908011489615,15mi","13.977956150853611, 79.98273526688673,15mi","13.728972148914936, 79.76744907993044,15mi","13.670530014961416, 79.39703019943212,15mi","13.977956150853611, 79.33371073268027,15mi","13.873476856779595, 78.95695990550676,15mi","13.670530014961416, 78.7733334519264,15mi","13.587455732476407, 78.49472779821825,15mi","13.916503462449306, 78.16863254444623,15mi","14.137656213146773, 78.178130464459,15mi","14.208257109895591, 77.77605185058475,15mi","14.465916047309937, 77.68740459713216,15mi","13.891917809329275, 77.5006121702142,15mi","14.640586293025871, 76.85475360934531,15mi","14.968099506164148, 77.02255019121543,15mi","15.533176008056206, 77.12069535609001,15mi","13.405821910766383, 79.75161923082055,15mi","13.257950630449079, 79.10892664328928,15mi","12.818165135296661, 78.41939934640426,15mi","14.755913578210931, 76.94765829979521,15mi","17.825286585069506, 81.87233026344859,15mi"]
Karnataka = ["11.763934046099253, 76.45382153431379,15mi","11.991619615882158, 76.8631438026417,15mi","12.054831676556326, 77.41034304556426,15mi","12.39591765123963, 77.45342960012509,15mi","12.297194501829276, 76.63663186835772,15mi","12.205540957511433, 76.89965028086205,15mi","12.111862179594695, 76.67537101438549,15mi","12.257349047216609, 76.46128626002152,15mi","12.432623763079752, 76.65702089258286,15mi","12.43063266555082, 76.39196357765603,15mi","12.31313099367048, 76.28594065168531,15mi","12.397970600235151, 77.0581739103298,15mi","12.118285799492476, 77.66549844018,15mi","12.22746635207862, 77.41419173817302,15mi","12.361605665185804, 77.45840310241499,15mi","12.547922180911183, 77.40255716863567,15mi","12.706866321645194, 77.26294233418734,15mi","12.675085405210586, 76.66725237387448,15mi","12.191077823433943, 75.79931348638739,15mi","12.3570596923046, 76.05527401620931,15mi","12.42296855119534, 75.75277520823795,15mi","12.388879841520788, 75.47121862543383,15mi","12.593344863697748, 75.88540930096386,15mi","12.684166072061965, 76.17860045330534,15mi","12.75906919473865, 76.4229264135899,15mi","12.78403198227849, 76.25538861225193,15mi","12.668274692641576, 76.62536792353998,15mi","12.395697946413815, 77.31180753586094,15mi","12.749991212684556, 77.65153696635186,15mi","13.023939020781318, 77.63662993977748,15mi","12.997760143989387, 77.55423270486436,15mi","13.0243753119708, 77.53587245143264,15mi","12.927063398666803, 77.54214180626299,15mi","12.909167832669354, 77.5819969905416,15mi","12.912223263947869, 77.6424514835485,15mi","12.934483135263736, 77.62229998587954,15mi","12.966778239812731, 77.59184883384643,15mi","12.952813302924792, 77.58647510113471,15mi","12.978996916745087, 77.63125620706573,15mi","12.961105078675004, 77.53542464037332,15mi","12.897382247981465, 77.48526980173055,15mi","12.973523133644917, 77.51366724750685,15mi","12.95494446337887, 77.48062190363775,15mi","12.931099806207996, 77.67349232410444,15mi","12.962685744525361, 77.71924741561548,15mi","12.98993313807356, 77.73608783124108,15mi","13.0128434058717, 77.70653766797352,15mi","13.017177542831131, 77.6569696521699,15mi","13.031417744779926, 77.68366012221801,15mi","13.052157443831184, 77.64076472335603,15mi","13.063300443655798, 77.58484183373142,15mi","13.04906207692129, 77.49968652453032,15mi","12.78227746578492, 77.63947381242379,15mi","12.805463805161214, 77.69006240925752,15mi","12.778626910599439, 77.75653956528544,15mi","12.902154340936677, 77.84795294955765,15mi","13.00296382441339, 77.93856446203802,15mi","12.860724693853896, 77.99469548746832,15mi","12.859161177196672, 78.18473910963787,15mi","12.956862224495449, 78.2721431349508,15mi","12.995633944883412, 78.26928475517052,15mi","13.16952797912135, 78.39013435950058,15mi","13.142783045126572, 78.10448984017502,15mi","13.319245476845172, 78.2061133710889,15mi","13.410100288228781, 78.04681161992659,15mi","13.770506408861015, 77.7803931602582,15mi","13.610393605722845, 77.49200205901607,15mi","13.316572766196456, 77.48925547709948,15mi","13.439487158197277, 77.72546152192636,15mi","13.33795368282081, 77.12945324602596,15mi","13.658438882785491, 77.17339855669144,15mi","13.316572766196456, 76.91796643844839,15mi","13.444829837439082, 76.56640395312465,15mi","13.570348420621409, 76.54168471587532,15mi","13.158830362992036, 76.64880141062238,15mi","13.011690828114174, 77.03606939355748,15mi","13.000986352565745, 76.83831549556287,15mi","12.928719082200235, 76.45104744532343,15mi","12.99295769284892, 76.11596445149922,15mi","12.792157219711315, 76.24505380157905,15mi","12.663560848759802, 76.60210945073598,15mi","12.81893990646253, 76.74493171039875,15mi","12.910545403462589, 74.85223313244839,15mi","12.966344940492975, 74.82718488900862,15mi","12.819844604583942, 74.85632264158141,15mi","12.903071304008249, 75.04750719355027,15mi","12.937450310201791, 75.13440926262703,15mi","12.948410736849707, 75.1850169381482,15mi","12.859218758815796, 75.24584838650192,15mi","12.927485867990319, 75.32917213508728,15mi","12.983281612790057, 75.27396376179145,15mi","13.012668980503301, 75.1359428285519,15mi","13.04653484787205, 75.01121279886365,15mi","13.0699394274443, 74.9882093099904,15mi","13.087366928196912, 75.01223517614692,15mi","13.089358564136747, 75.08022326548344,15mi","13.128690072708928, 75.14872254346157,15mi","13.051514731331041, 75.22233370785601,15mi","13.009680595353844, 75.30565745644137,15mi","13.077906437760584, 75.3598434631239,15mi","13.142684521691422, 74.76367377313825,15mi","13.154392329032207, 76.31842187305422,15mi","13.25787981268177, 76.47622601493813,15mi","12.948354572050876, 76.56937429313349,15mi","13.326136129362432, 76.64718050197904,15mi","13.289877352845238, 76.05541496991437,15mi","12.805202019501142, 75.87131013771648,15mi","13.472182471003729, 76.35677704194546,15mi","13.733630555428293, 76.88514729428535,15mi","13.945493372527988, 76.62036847520582,15mi","14.081078876312688, 76.19378037493422,15mi","14.240348412240937, 76.38991283351166,15mi","14.308046154238122, 76.65216847684324,15mi","14.589688735159156, 76.66927683125398,15mi","15.142720274035465, 76.91276896821043,15mi","15.101491106901223, 77.00916716012175,15mi","15.238105528278357, 77.04821452899722,15mi","15.319325539412397, 77.01160762067647,15mi","15.140364537682425, 77.09946420064628,15mi","15.431098581024006, 76.84199560845596,15mi","15.531055057297515, 76.85663837178426,15mi","15.385220063855273, 76.68702636323142,15mi","15.249878495775034, 76.67116336962576,15mi","15.1921846807099, 76.64309807324652,15mi","15.60863493527614, 76.89202505206899,15mi","15.794237025293382, 77.00428623758599,15mi","15.761357851809638, 76.74071649767654,15mi","15.667388042018583, 76.53571781108032,15mi","15.991399667853898, 77.03235154491722,15mi","16.00899406021883, 76.84931700331344,15mi","16.14148855468648, 77.20806470485685,15mi","16.23757955455891, 77.11044628266816,15mi","16.416745687858054, 77.38499810246005,15mi","16.506851978149474, 77.5009199788091,15mi","17.222016987944624, 77.28800557420246,15mi","17.714956285115516, 77.1111233460386,15mi","17.764506741073077, 77.13540129892382,15mi","17.32468451508629, 76.83019274836657,15mi","17.331306260181947, 76.87528037515344,15mi","17.447148071072323, 76.80244651649772,15mi","17.32468451508629, 76.77470028462888,15mi","17.281637356500287, 76.82325619039936,15mi","17.526539965447, 76.20590253131762,15mi","17.20213925405539, 76.5215159188257,15mi","17.215391300120565, 75.94924986365463,15mi","16.93026379499912, 76.24405357726108,15mi","16.837337926651962, 75.70647033480226,15mi","16.57823308809051, 75.97699609552348,15mi","16.72443804580619, 75.06137044385169,15mi","16.155612067531866, 74.8185909060226,15mi","16.328764351620524, 75.2798720108421,15mi","16.17559894786071, 75.65444614107147,15mi","15.955632535283465, 76.11225896690736,15mi","16.155612067531866, 76.52151588697278,15mi","16.34207743228571, 76.12613208284178,15mi","15.769662135664127, 76.75801114904489,15mi","15.439368633210107, 76.52433038734654,15mi","15.357444176038516, 76.14497850147258,15mi","15.278415109518821, 76.3877637084319,15mi","15.358817788268, 75.12510535449103,15mi","15.361915903383773, 75.14392366841476,15mi","15.380946171952157, 75.12464637122459,15mi","15.317652752591352, 75.1416287520826,15mi","15.343769146183552, 75.01035953788283,15mi","15.40439969206534, 75.01035953788283,15mi","15.460588867304185, 75.0071466550178,15mi","15.233240929216638, 74.59987524703376,15mi","15.459217055016003, 74.4899818215387,15mi","15.641597129657308, 74.51342582041042,15mi","15.742604768029166, 74.4964390905291,15mi","15.692588191072911, 74.36654055769972,15mi","15.691626213463584, 74.24163812228689,15mi","15.838755879668573, 74.4035116686542,15mi","15.860864171870789, 74.60435478479806,15mi","15.98097548237922, 74.51742269217007,15mi","16.030920588167263, 74.69328532123134,15mi","16.39839795100783, 74.38752415692143,15mi","14.46460961417405, 75.92223225872901,15mi","14.431653963252971, 75.91596321561798,15mi","14.40996995259764, 75.95984651739518,15mi","14.403898051593917, 75.99074394415668,15mi","14.48238629105645, 75.8873047328247,15mi","14.484987636522273, 75.85506393968225,15mi","13.92832881713619, 75.56860659654723,15mi","13.932630781747278, 76.5895376425947,15mi","13.341939803885163, 74.7422415319479,15mi","13.336463503527817, 77.11169272911752,15mi","15.266978742748726, 76.3800331655677,15mi","18.32694647167443, 77.2580245897622,15mi","15.85253941227526, 74.48334660826461,15mi","15.594215809284185, 73.81819992789548,15mi","15.549307266871356, 73.75852668613804,15mi","15.403736430488951, 73.82752387192008,15mi","15.277852301935726, 74.00281401958253,15mi","15.042066478507422, 73.9804365539235,15mi","14.98443012738481, 74.04570416209569,15mi","15.418118349476813, 74.03638021807109,15mi","15.491810041110906, 73.93195204499558,15mi","15.534934463075627, 74.038245006876,15mi","15.38216168722416, 74.15945627919578,15mi","15.613972457881127, 74.1035126150482,15mi","15.701956189456268, 73.81633513909055,15mi","15.658866848747033, 73.93381683380049,15mi","16.388342764932453, 74.38696052951039,15mi","16.443794640756426, 74.58835772044172,15mi"]
Telangana = ["17.71792824705595, 80.89920553008321,15mi","17.47124088484438, 80.60120011878112,15mi","17.332799755660368, 80.16203424949384,15mi","17.078095494535955, 79.95029356251605,15mi","17.997843242423794, 80.83254642492354,15mi","18.422462540882762, 80.49925089912516,15mi","18.612086527925047, 80.29143132042964,15mi","18.53031373387155, 79.87971331797281,15mi","18.69753426109806, 79.40917845802215,15mi","18.96103505851648, 79.49936429242945,15mi","19.16486991042377, 79.4758375494319,15mi","19.40544093930068, 79.56994452142203,15mi","19.394345453259785, 79.12685752830183,15mi","19.5865598203431, 78.7739563646782,15mi","19.741642665947133, 78.46418758187734,15mi","19.46830106138072, 78.37008060988721,15mi","19.172277365295955, 78.31910600005922,15mi","19.120418250056677, 77.95444148359746,15mi","18.916528779289578, 77.9936527219267,15mi","18.723531564040176, 78.14657655141065,15mi","18.44106243847554, 77.86817675927318,15mi","18.1245922976633, 77.75446416271669,15mi","17.7478068216481, 77.6485938192278,15mi","17.504899880742382, 77.7779909098065,15mi","17.269156602593604, 77.55056572749703,15mi","17.03311140097751, 77.58977696582625,15mi","16.79676790056584, 77.54272347983118,15mi","16.56012973745645, 77.53488123331115,15mi","16.1952145094405, 77.63683045296712,15mi","16.00307974868784, 77.80151765394986,15mi","15.950304422407182, 77.54272348654243,15mi","15.889972760905529, 78.04854846098938,15mi","16.14249015573343, 78.45242421578037,15mi","16.217806336370092, 78.82493097990796,15mi","16.518782013137226, 79.17783212487097,15mi","16.684119566540982, 79.37780944034999,15mi","16.76298038135954, 79.679735975485,15mi","16.85306700158202, 79.97382026295415,15mi","16.90184602670675, 80.0169526251163,15mi","16.909349380347038, 80.43259175549827,15mi","17.15679154224377, 80.73451829063328,15mi","17.38519520214479, 81.16976303608763,15mi","16.23286612267498, 77.95444146297248,15mi","16.41725468431759, 78.06423293029431,15mi","16.499984671078977, 78.3661594654293,15mi","16.492465222354582, 78.81708870621536,15mi","16.785506046723242, 79.11509411751744,15mi","16.7779977884417, 78.83277320154703,15mi","16.860572287480913, 78.58182127624003,15mi","16.853067002238866, 78.22892013127702,15mi","16.69163152529384, 77.93483584380787,15mi","16.639041623698624, 77.67212054700208,15mi","16.98436639062692, 77.75054302366053,15mi","16.943110734886254, 78.15833990228442,15mi","16.860572287480913, 78.67592824823015,15mi","16.841808515979828, 79.18175322267712,15mi","17.093087768867758, 78.89159005904087,15mi","17.04435841873351, 78.50339879958157,15mi","17.153044859754807, 78.22107788361119,15mi","17.347771397791114, 77.87601898631404,15mi","17.609576799843094, 77.97012595961371,15mi","17.5287741832284, 78.25603126851142,15mi","17.52708214410706, 78.33647187667373,15mi","17.549641367638223, 78.4021256083356,15mi","17.57276165683359, 78.48374916661794,15mi","17.557536432481438, 78.57010452538042,15mi","17.4938021693122, 78.62511170596198,15mi","17.42665962259763, 78.64285595776249,15mi","17.367395678720843, 78.64699628318262,15mi","17.32618182225789, 78.63871563234238,15mi","17.326746458170312, 78.57542780092058,15mi","17.270274282245268, 78.56714715008033,15mi","17.309241937915456, 78.50267636853847,15mi","17.26519093662288, 78.5245609457591,15mi","17.221129406690284, 78.50267636853847,15mi","17.393361294211456, 78.48907244215809,15mi","17.31488873953677, 78.42696756085631,15mi","17.36287954363613, 78.39975970809553,15mi","17.399569917265406, 78.381423981235,15mi","17.46559403016006, 78.3601308790744,15mi","17.485904331226227, 78.40153413327559,15mi","17.441331534938108, 78.50090194335844,15mi","17.479134482738857, 78.56892157526038,15mi","17.2290386590181, 78.42874198393751,15mi","17.266320579462505, 78.39029610503641,15mi","17.421580607242504, 78.56596419786145,15mi","17.52087786605027, 78.53698192093299,15mi","17.40916464768345, 78.48966391613163,15mi","17.373040691413237, 78.4435288614503,15mi","17.825642251505165, 78.07944356268469,15mi","17.75778479585069, 78.28815068982541,15mi","17.849870801085384, 78.6826580642987,15mi","17.910427734063244, 78.8913651914394,15mi","18.15486659682566, 78.6826580642987,15mi","18.130679895672092, 78.85318705842586,15mi","18.333743898615406, 78.3136027789261,15mi","18.54863509158416, 78.5146742794641,15mi","18.727103135863576, 78.44595364003972,15mi","18.970383798924146, 78.60375658919156,15mi","19.143595335179597, 78.98808312819457,15mi","19.49906949514242, 78.85573226708095,15mi","19.681308218208372, 78.57321408278072,15mi","19.630973420958263, 78.87863914890785,15mi","19.201292230871637, 79.27569174935519,15mi","19.350248798854988, 79.47421804102562,15mi","18.475114364055678, 79.09405388602651,15mi","18.712134985741777, 78.08333936220068,15mi","18.669562540074374, 77.9906172126437,15mi","17.953066422124593, 79.67591008412803,15mi","17.401540278395956, 78.5548239565754,15mi","18.671486566816785, 78.10333497453979,15mi","18.693483227673546, 78.30821884677869,15mi","18.71288967359528, 77.92235422072878,15mi","19.487261968245466, 78.70745211062528,15mi","18.97017083882513, 79.37590197418332,15mi","17.86222355130803, 79.22288333071823,15mi","18.01546535825944, 80.5517294450204,15mi","17.14792840126028, 80.20542409402044,15mi","17.38633823847187, 78.47389733902065,15mi","19.13003421868956, 77.3141770938115,15mi","18.428550256494017, 79.12623997695081,15mi","16.353612486720216, 78.17591366490441,15mi","17.46317864058102, 78.57859430560204,15mi","15.835171092485249, 78.03094863425326,15mi","16.832142045444673, 77.55578547823008,15mi","17.007168298071186, 79.96410737681643,15mi","17.133316004596853, 79.62628669094755,15mi","16.75461841570485, 78.13776429383778,15mi","18.31484716295213, 78.33306687785574,15mi","18.44007833226129, 79.8690953089158,15mi","17.249114028635404, 80.1453997219611,15mi","17.604723811186286, 78.05886122717877,15mi","17.341970224357773, 77.90538803792975,15mi","16.967837507238368, 78.72391171392452,15mi","17.259312466254812, 78.88328771814466,15mi","17.503420958083783, 78.87541729818318,15mi","17.451984455609463, 78.6853972405936,15mi","17.5430015825021, 78.67927975329606,15mi","17.50683356767171, 78.86647486460099,15mi","17.637471012027838, 78.39053435285184,15mi","17.667784049886286, 78.59852892096843,15mi","17.14943585670952, 78.28898406371258,15mi","17.31420550713367, 78.13727037873342,15mi","17.465990055744925, 78.34893543922854,15mi","17.241771710932685, 78.53123656069542,15mi","17.513834391161918, 79.29469897542927,15mi","17.503949308020967, 78.50098145815579,15mi","17.455798726182856, 78.43455816841588,15mi","17.51788525456291, 78.45315668954305,15mi","17.56285305344828, 78.45249245664564,15mi","17.484310478046133, 78.58467480322811,15mi","17.473539896633497, 78.22333210704286,15mi","17.56221978164603, 78.16355114627693,15mi","17.41802069926569, 78.4469203062429,15mi"]
North_India = ["28.602601655387524, 77.12854992281093,100mi","28.639030360050217, 76.98791245356583,100mi","28.581683171901872, 77.02249543778042,100mi","28.698368559659617, 76.9525609585909,100mi","28.74285014642609, 77.0816707663254,100mi","28.704435344690705, 77.2691873918446,100mi","28.611372683860917, 77.30530739757985,100mi","28.528355966595242, 77.22307674622513,100mi","28.46351695726093, 77.14161460563072,100mi","28.53233980174745, 77.40732957192161,100mi","28.551642058524735, 77.47256089471496,100mi","28.644484663579878, 77.50277329685082,100mi","28.49674199683428, 77.36475755073016,100mi","28.433964084027874, 77.2665672437886,100mi","28.484672218005738, 77.20888902152923,100mi","28.598676485630737, 77.58448411171827,100mi","28.711352777644954, 77.5714378471596,100mi","28.5653126374748, 77.22477388360787,100mi","28.613938250373923, 77.31023354122114,100mi","28.708723432549466, 77.41415248487888,100mi","28.61274517387351, 76.98861329696979,100mi","28.579702558197162, 77.77157029371776,100mi","28.726300167408795, 77.63480523801384,100mi","28.840535986101198, 77.55586701794311,100mi","28.850216697892222, 77.09906671020394,100mi","28.855695894497504, 77.30425639549794,100mi","28.45412543220475, 76.8688076437629,100mi","28.475189586388023, 77.68488217719792,100mi","28.15878745970337, 77.35929803691556,100mi","28.98686249423508, 77.01820988790672,100mi","28.968367432708774, 77.73703201580284,100mi","28.725159337625154, 77.3296994766617,100mi","28.546214804209153, 76.89032142423252,100mi","28.561599617657475, 76.85449481691049,100mi","28.54236824927659, 76.89629252544964,100mi","28.555306101939824, 76.8755927078874,100mi","28.533275834467407, 76.9177884898412,100mi","28.59830429142419, 76.88275802935125,100mi","28.616477100177285, 76.91380775569462,100mi","28.59201297144605, 76.9552073908191,100mi","28.541668860611523, 76.9360998669155,100mi","28.51753710867514, 76.96277078569761,100mi","28.62486348997103, 76.94525555545265,100mi","28.545865122948708, 76.92774032520767,100mi","28.579198354284618, 77.04090161388459,100mi","28.510759267105993, 76.99076988014764,100mi","28.547186799057826, 77.02407544597013,100mi","28.56760757753075, 77.00123159258993,100mi","28.597522643796555, 77.00614507963698,100mi","28.637779481787266, 77.07558902350735,100mi","28.616215238172373, 77.06707231344208,100mi","28.580264991174634, 77.18204789932311,100mi","28.596947434994327, 77.17647928120351,100mi","28.69037763590823, 77.32224605066952,100mi","28.582853818238775, 77.38775920570079,100mi","28.600686238752147, 77.46113393857073,100mi","28.55207139904575, 77.46506472804803,100mi","28.567895262623797, 77.50764827837433,100mi","28.508327627940837, 77.49159755555904,100mi","28.527036067750082, 77.53516380320056,100mi","28.46427774138119, 77.55645557951088,100mi","28.405227862993154, 77.53712919897816,100mi","28.444118073582807, 77.58659163051104,100mi","28.392261285221075, 77.54105998823906,100mi","28.36084677623058, 77.42739466488183,100mi","28.440085676590535, 77.35074427429448,100mi","28.470324891193375, 77.65144965371945,100mi","28.467157379490033, 77.73628918898798,100mi","28.416752376874836, 77.8371794474211,100mi","28.562287213241245, 77.1731450959779,100mi","28.551263694819816, 77.18846077146593,100mi","28.566584204318488, 77.21409325613686,100mi","28.563127942374106, 77.23674769313287,100mi","28.551450543413377, 77.25599864635046,100mi","28.53790313810934, 77.25791310578647,100mi","28.52986730219968, 77.22738811366797,100mi","28.53463281339946, 77.26780447976823,100mi","28.553505859229162, 77.29269245243628,100mi","28.539631525680115, 77.33202432395672,100mi","28.668300315616385, 77.10222321014943,100mi","28.67193827110463, 77.10254215687077,100mi","28.658505192738172, 76.80002118996359,100mi","28.661583758716, 76.72873659735856,100mi","28.73278532370033, 76.82633429418325,100mi","28.796811312703667, 76.640388354641,100mi","27.528053335233878, 76.65415278541319,100mi","27.161252287466525, 77.95536662118708,100mi","26.75001873839896, 77.98696647256914,100mi","26.374101844477952, 78.15760567298933,100mi","26.572106553614503, 78.67584323565515,100mi","26.639915322294325, 78.57156372609435,100mi","26.41939009244004, 78.7516828789721,100mi","26.629129546243917, 79.55431908776988,100mi","26.903412084507707, 80.5435440467995,100mi","26.560577303043573, 80.14095637207711,100mi","27.016377566059372, 82.05701808697658,100mi","30.862808443952456, 75.75105686468308,100mi","30.53738495601962, 75.82201917734824,100mi","30.34704891780325, 75.43566880839337,100mi","19.100801927503362, 72.88711797660034,100mi","19.111124844333197, 72.83398417948823,100mi","19.11487847251788, 72.8841385113417,100mi","19.083572120868467, 72.85200152424056,100mi","19.090429792210855, 72.86384126861395,100mi","19.089640325612958, 72.87846093062427,100mi","19.093587620953524, 72.86300585935622,100mi","19.06935299821293, 72.86473835366229,100mi","19.09626771790743, 72.87506618147941,100mi","19.101920071286642, 72.88066761311981,100mi","19.110069351788596, 72.88603749517442,100mi","19.105610361255188, 72.86748699353124,100mi","19.086696755209818, 72.8759486258597,100mi","19.112706412948572, 72.86658405037507,100mi","19.119618072715415, 72.87577473657821,100mi","19.114478660949914, 72.88871672327242,100mi","19.11518755483112, 72.87446178140634,100mi","19.087006682964198, 72.8722110011117,100mi""19.111124844333197, 72.83398417948823,100mi","19.100801927503362, 72.88711797660034,100mi","19.11487847251788, 72.8841385113417,100mi","19.083572120868467, 72.85200152424056,100mi","19.090429792210855, 72.86384126861395,100mi","19.089640325612958, 72.87846093062427,100mi","19.093587620953524, 72.86300585935622,100mi","19.06935299821293, 72.86473835366229,100mi","19.09626771790743, 72.87506618147941,100mi","19.101920071286642, 72.88066761311981,100mi","19.110069351788596, 72.88603749517442,100mi","19.105610361255188, 72.86748699353124,100mi","19.086696755209818, 72.8759486258597,100mi","19.112706412948572, 72.86658405037507,100mi","19.119618072715415, 72.87577473657821,100mi","19.114478660949914, 72.88871672327242,100mi","19.11518755483112, 72.87446178140634,100mi","19.087006682964198, 72.8722110011117,100mi","19.08753844194751, 72.88177681736394,100mi","19.080802701987487, 72.88852915824788,100mi","19.09910183548748, 72.85007516686277,100mi","19.07157895409399, 72.85367069005865,100mi","19.0637629813346, 72.87776069547111,100mi","19.065462137196374, 72.86229994572878,100mi","19.113634201531866, 72.8613142311881,100mi","19.207550520852834, 73.09044344475083,100mi","19.222015639137823, 73.16273294154512,100mi","19.219902836212615, 72.97736201613552,100mi","19.130916664846218, 72.91781292151659,100mi","19.122129927824748, 72.92831022290797,100mi","19.177547498842547, 73.16777165543586,100mi","19.2005931933618, 73.07016580619138,100mi","19.159876949260155, 73.07992639111583,100mi","19.069189598438623, 73.07097918826842,100mi","19.122224682831693, 72.99533465510395,100mi","19.122224682831693, 73.00021494756618,100mi","19.174474495883064, 73.1555709242803,100mi","19.15065678022793, 73.14581033935585,100mi","19.169096602796195, 73.13686313650844,100mi","19.296258992497847, 72.99579911961585,100mi","19.450456318588564, 73.09740476328214,100mi","19.206416750474222, 73.13482960251659,100mi","18.752072571308563, 73.38214112452027,100mi","18.779976758907683, 73.40488932953362,100mi","18.757424592397378, 73.3821062027492,100mi","18.737321207058827, 73.483076878271,100mi","18.762327493866664, 73.36087647097283,100mi","18.766679730496698, 73.38012839304334,100mi","18.762942385872904, 73.35920851214537,100mi","18.774901597085726, 73.38091782251118,100mi","18.777891267328556, 73.30750088200136,100mi","18.796575504406274, 73.35131421746689,100mi","18.763316124062253, 73.32328947135832,100mi","18.533160276614694, 73.8817413447387,100mi","18.52840246040329, 73.88111409681902,100mi","18.516507340619594, 73.87358712178299,100mi","18.509964672139642, 73.86982363426497,100mi","18.521265487815764, 73.89616804689112,100mi","18.541486136271693, 73.8942863031321,100mi","18.524239262595028, 73.89679529481079,100mi","18.541486136271693, 73.89930428648945,100mi","18.54802759849387, 73.88048684889935,100mi","18.521860246908464, 73.83908848620112,100mi","18.533160276614694, 73.83281600700442,100mi","18.539107360624964, 73.83218875908476,100mi","18.545648913946774, 73.83908848620112,100mi","18.545054237633234, 73.85539693211255,100mi","18.520075963425466, 73.83783399036179,100mi","18.516507340619594, 73.83281600700442,100mi","18.55219021672053, 73.85978766755025,100mi","18.548622264453606, 73.8227800402897,100mi","18.542080825007904, 73.82215279237003,100mi","18.51234385325941, 73.87546886554199,100mi","18.510838821089592, 73.79330269769964,100mi","18.566633071843256, 73.80935213498948,100mi","18.57677552239216, 73.88852935895265,100mi","18.58691736956548, 73.84145100956914,100mi","18.61324470360951, 73.47295590747903,100mi","18.63368289710194, 73.66059331704923,100mi","18.641857486379656, 73.70372835373205,100mi","18.631639188326005, 73.66706357255167,100mi","18.474199980423062, 73.70804185740033,100mi","18.47010871817229, 73.83529021561462,100mi","18.5506424180853, 73.84459661077155,100mi","18.60763592042311, 73.92800208389956,100mi","18.69704352278927, 73.7697869132733,100mi","18.70076216454403, 73.811008473484,100mi","18.685887107499585, 73.88216473813341,100mi","18.69564901107233, 73.76046298893992,100mi","18.69378964425012, 73.72022289444851,100mi","18.675659748020298, 73.7295468187819,100mi","18.715635914484263, 73.7565371260627,100mi","18.729578867147932, 73.76193518751887,100mi","26.96432161857182, 75.7085842802668,100mi","27.019370916612427, 75.84984987973219,100mi","26.987319807963086, 75.9344094849082,100mi","26.995645649577565, 75.88956019155516,100mi","26.932353806097357, 75.86339810376592,100mi","26.931937294651323, 75.9344094849082,100mi","26.956508837491253, 75.73959536690603,100mi","26.98149135220953, 75.77369951705988,100mi","26.96691889217574, 75.68073066617599,100mi","26.961922185977308, 75.6564372989431,100mi","26.907360397172706, 75.61812852753741,100mi","26.99023392257457, 75.58495873766174,100mi","27.033131980713335, 75.72878575612927,100mi","27.100021039478953, 75.74273431644598,100mi","27.115039993049468, 75.63223847809853,100mi","27.0687795127729, 75.58769971535368,100mi","27.174364229778405, 75.72407460391624,100mi","27.17722900475643, 75.62102623266537,100mi","27.125172840349833, 75.83895433795624,100mi","27.080415120320215, 75.82343618751338,100mi","27.021816277283637, 75.79922787282253,100mi","27.25393601306213, 75.63615310640206,100mi","27.238890539705956, 75.53799872051844,100mi","20.28988481260238, 85.811374748993,100mi","20.28988481260238, 85.811374748993,100mi","20.264422376148648, 85.83780130358629,100mi","20.2600933417198, 85.81661130263663,100mi","20.303916575626324, 85.87188804780708,100mi","20.313385902452122, 85.80891020810823,100mi","20.265122570223696, 85.77826051557201,100mi","20.255577775996645, 85.7611590499525,100mi","20.244204489111535, 85.75271655426691,100mi","20.257202463269614, 85.7791264125654,100mi","20.29442689964852, 85.74401549569056,100mi","20.308750798736988, 85.73863295296177,100mi","20.22246352879249, 85.80770757429856,100mi","20.213624403991872, 85.81104998297903,100mi","20.20307382356408, 85.78826083288506,100mi","20.20991752479379, 85.73630157067079,100mi","20.35422990200635, 85.82743494336609,100mi","20.379081565339277, 85.8303343514366,100mi","20.295191179318174, 85.74832252315639,100mi","20.211012169733007, 85.70176632752786,100mi","20.218135142377612, 85.71160587585693,100mi","20.175920177600293, 85.67927593134709,100mi","20.16694802413321, 85.6674684733522,100mi","22.612221935738077, 88.4015944438548,100mi","22.58027684957757, 88.42068478177326,100mi","22.594230787456436, 88.26716664767912,100mi","22.511220797757517, 88.25682604797329,100mi","22.51551993714675, 88.29871154362634,100mi","22.57395253419063, 88.31416396746215,100mi","22.51875187882486, 88.34215326346666,100mi","22.50313012734747, 88.32291062246357,100mi","22.533294680921752, 88.2867577817911,100mi","22.52009849827673, 88.41329272698304,100mi","22.479694190963468, 88.4302029266524,100mi","22.46657225245034, 88.39127400878573,100mi","22.495838570567496, 88.3711938750803,100mi","22.487462455674752, 88.3216563317473,100mi","22.59445364275651, 88.4778929263999,100mi","22.563374176328672, 88.50432485320397,100mi","22.585657133114736, 88.5413459151384,100mi","22.58207138002485, 88.56814240901467,100mi","22.642299636573657, 88.49260736330757,100mi","22.612188804897865, 88.51552030734673,100mi","22.63387643751443, 88.50581143275387,100mi","22.667028598316985, 88.46988859631846,100mi","23.414806613971532, 85.38033382994062,100mi","23.213020806329837, 85.29793637160745,100mi","23.14232355610235, 85.43251888688496,100mi","23.16252658083508, 85.56710140216249,100mi","23.14232355610235, 85.182579929941,100mi","23.104434678503036, 85.28145687994079,100mi","23.08169621875709, 85.03014463202462,100mi","23.305123566939027, 85.02053159521907,100mi","23.30890724979656, 85.4544915424405,100mi","23.408505448088707, 85.25673764244085,100mi","23.35430304337391, 85.62340633202349,100mi","23.272327141411296, 85.63439265980124,100mi","23.542025827691955, 85.182579929941,100mi","23.470243927503137, 85.10704892646892,100mi","23.382037275942924, 84.96010679244141,100mi","23.67369095560393, 85.47189002978439,100mi","23.662121313183746, 85.22872087360234,100mi","23.511622936185304, 84.75501472519574,100mi","23.659228742597207, 84.75185668420636,100mi","22.862238797141817, 86.18335412607772,100mi","24.121770094745433, 85.41377683868043,100mi","21.16409225911337, 72.96919367733517,100mi","21.16409225911337, 72.96919367733517,100mi","21.12310537652643, 72.70140193775234,100mi","21.029561672997264, 72.72749446622451,100mi","21.176898333474572, 72.64509700789134,100mi","21.20634809581111, 72.88267634608533,100mi","21.34455530452603, 72.75633357664113,100mi","21.316412518224144, 72.94859431275188,100mi","21.506910180023752, 72.70964169257053,100mi","21.030843493422633, 73.16008113145857,100mi","20.939807050640812, 72.95408748562562,100mi","21.404660431060293, 72.92387508423678,100mi","21.480076564912775, 72.9870464689589,100mi","21.25883093288261, 73.29466364673608,100mi","21.446847141493937, 73.31800959326382,100mi","34.48256286186215, 74.47851779336474,100mi","33.78389864925067, 74.33080422840482,100mi","33.538005535768534, 75.03771914642735,100mi","32.39612086449496, 75.61802243734135,100mi","32.90249410182749, 77.81262397388888,100mi","32.60968007646597, 74.92165848824455,100mi","31.437867997913628, 74.9849643017988,100mi","32.36047839283484, 77.42223812363763,100mi","30.760284634983062, 77.99199044889292,100mi","30.606029134913328, 76.50430382622976,100mi","29.031615795170755, 76.07171409526633,100mi","28.430239862514945, 73.55003252202181,100mi","30.013966083026673, 74.42576294285568,100mi","29.79445717225792, 74.97441332699256,100mi","29.00393628356545, 79.00488346808423,100mi","29.702852554756635, 79.2053518776727,100mi","28.430239843756063, 79.37416738048405,100mi","27.946662382897742, 80.99901659504327,100mi","26.630764302276116, 81.79199167759292,100mi","25.222318545040626, 82.37928651307544,100mi","25.76225034389052, 80.44338872796081,100mi","21.493994218946973, 82.09103901898823,100mi","22.189413937740987, 86.19294727511712,100mi","22.241433373954745, 71.09642644868799,100mi","25.832855167830658, 74.5615087764639,100mi","26.04304622010163, 86.93976854472687,100mi","22.623971491927087, 89.57500557624961,100mi","22.18099945195887, 85.92826342151612,100mi","21.26607165900897, 76.61176885903402,100mi","30.445896797187782, 78.27205569268874,100mi","30.559903844847412, 76.46093029787144,100mi","29.68724257047001, 78.19762588194283,100mi","21.17278541365989, 77.63789864116247,100mi","30.282577516428837, 75.75496348623426,100mi","30.219131210812712, 76.23885522673439,100mi","30.107067282686014, 75.30995590345292,100mi","29.66129647211253, 75.34451959605174,100mi","30.68840391448488, 74.6316433666594,100mi","31.54593771805766, 77.67627797522103,100mi","31.57256972177027, 78.34998773523408,100mi","31.157435372238208, 78.13120569976591,100mi","31.10690155937116, 78.13467843048763,100mi","29.804626154894564, 74.96319745473414,100mi","29.91108900863554, 75.51560528437183,100mi","29.819842084791542, 75.83345899586969,100mi","30.099021839222868, 75.8619562251764,100mi"]
TamilNadu = ["13.421315202184045, 80.31734326194108,15mi","13.40517762194002, 80.11826181333329,15mi","13.333819564899, 80.19248077443707,15mi","13.273488581412128, 80.2649534070443,15mi","13.213142608096446, 80.31908959043763,15mi","13.310878566858198, 80.04404285222952,15mi","13.433205356869474, 79.95498009890501,15mi","13.53000320808228, 79.9811750263534,15mi","13.332969937102952, 79.89123910878058,15mi","13.283686420326735, 79.77598142684127,15mi","13.253091615087266, 79.8816343008831,15mi","13.201241636869335, 79.92616567754537,15mi","13.124721577189113, 80.00562362413882,15mi","13.104312197086509, 80.09206688471852,15mi","13.122170494376606, 79.90171707640653,15mi","13.133224982515246, 79.77598142465426,15mi","13.164718384964276, 80.29593989762049,15mi","13.172367202991527, 80.24880760572938,15mi","13.198658191559241, 80.17761820651883,15mi","13.115951560868291, 80.15307013782554,15mi","13.086304252495855, 80.2699189448056,15mi","13.127426979204975, 80.27335567442266,15mi","13.11882046567636, 80.22818722802701,15mi","13.080087428830106, 80.21493127093264,15mi","13.040391709001334, 80.23162395764406,15mi","13.055218567563037, 80.27040990617947,15mi","13.008343528276347, 80.21738607780196,15mi","13.03800019694648, 80.15257917645167,15mi","13.003559860711194, 80.12263053297377,15mi","12.979161730008311, 80.20903973477415,15mi","12.965765659254565, 80.24340703094475,15mi","12.941842311076163, 80.2326058807197,15mi","12.903081616864975, 80.22425953736399,15mi","12.919830803113006, 80.17172667036034,15mi","12.951890397152887, 80.13883225831134,15mi","12.926530163219455, 80.09808246428048,15mi","12.891595812174888, 80.16436224975237,15mi","13.049000959388879, 80.09513669603729,15mi","13.092042719573827, 80.19627474151314,15mi","13.09430808702084, 80.26607715568056,15mi","13.074801643325989, 80.26634417418555,15mi","13.231640513077783, 80.00169563177566,15mi","13.220043476531856, 79.90709224173334,15mi","13.126564915225078, 80.00309716347999,15mi","13.128612272894536, 79.909895305142,15mi","13.129977168528262, 79.77044290056106,15mi","13.205034728360483, 79.72419235431815,15mi","12.965452848165452, 79.93722517489765,15mi","12.924475465777192, 79.8734554823506,15mi","12.839767582701393, 80.06336302828743,15mi","12.782368585469323, 80.2175315163781,15mi","12.73384259183802, 80.18599705303066,15mi","12.685990968842255, 79.98697955101568,15mi","12.64838694754844, 80.03393086214535,15mi","12.605990323178732, 80.05565460356247,15mi","12.621718923078495, 80.17408403257843,15mi","12.530069176661355, 80.14044727167449,15mi","12.443177016260618, 80.08859059861426,15mi","12.507493706421903, 79.87836084296464,15mi","12.618299744433042, 79.76343524320949,15mi","12.632659987653277, 79.66883185316715,15mi","12.425384473448663, 79.82860646640773,15mi","12.347356681532435, 80.00309716359693,15mi","12.29532521857199, 79.9834757197363,15mi","12.19397126468428, 79.91830448948788,15mi","12.23027140671285, 79.64640733884768,15mi","12.16177641392406, 79.6036606218656,15mi","12.123411499076978, 79.61977823339367,15mi","12.038441005899719, 79.84332254023444,15mi","11.99800204797216, 79.82229956466948,15mi","11.962307306858804, 79.8124459813775,15mi","11.942467610782238, 79.80717335003038,15mi","11.946038863382995, 79.83150857163244,15mi","11.927785300033507, 79.82501917920521,15mi","11.949213270603375, 79.77797108410792,15mi","11.926991638963798, 79.77959343221472,15mi","11.914689595525381, 79.80392865381677,15mi","11.90278386151146, 79.8128515684042,15mi","11.894052658437644, 79.79906160949636,15mi","11.863888165447447, 79.79094986896234,15mi","12.025387856518165, 79.73254533711743,15mi","12.029354694847111, 79.65061675631851,15mi","12.067433345551468, 79.59586250771389,15mi","12.123748093030532, 79.62506477363635,15mi","12.157848431105265, 79.6015407260877,15mi","12.10669628922229, 79.7434961844002,15mi","12.202251619918338, 79.74065707578896,15mi","12.201855195775085, 79.83515885301026,15mi","12.226828758744325, 79.64980557960689,15mi","12.266068160429429, 79.51555627376892,15mi","12.29262080563047, 79.57031052237353,15mi","12.25378170245577, 79.4157818652005,15mi","12.230792599406653, 79.41172599493349,15mi","12.169346400376803, 79.44052267382926,15mi","12.158244924126203, 79.42673271492143,15mi","12.133264908716344, 79.42511036681462,15mi","12.119386110269893, 79.47945902839254,15mi","12.195512329880318, 79.55246469319869,15mi","13.5427368446737, 80.06761828693308,15mi","8.09005720438742, 77.53233102994616,15mi","8.117266110765764, 77.5281668880148,15mi","8.188989833192402, 77.70222802074628,15mi","8.273887416171961, 77.67890882593058,15mi","8.335694547696491, 77.86296389929736,15mi","8.286249620500566, 77.88378460895423,15mi","8.446922723022126, 77.91376643086014,15mi","8.484815391947834, 77.78301237421495,15mi","8.431270316172268, 78.02703109139354,15mi","8.406554699514949, 77.61061689825603,15mi","8.50128930038502, 77.64642851886585,15mi","8.52105705586601, 77.5514860828305,15mi","8.188165495768498, 77.40907242877746,15mi","8.250810264051855, 77.31496282112839,15mi","8.183219435393006, 77.25583200570286,15mi","8.308500609022893, 77.22002038509304,15mi","8.368654361820534, 77.29330928308524,15mi","8.399139707050146, 77.2608289760205,15mi","8.456808126571987, 77.19253704834595,15mi","8.348878807341993, 77.15006280064593,15mi","8.574589597280681, 78.09782151552619,15mi","8.630584791669719, 78.02120130398887,15mi","8.646229025563182, 77.91293361377312,15mi","8.725263620658671, 77.75636187715342,15mi","8.719501245072745, 77.79134066937696,15mi","8.721147647169646, 77.72055025654359,15mi","8.673399045316504, 77.567309833469,15mi","8.712092345864097, 77.44654971745909,15mi","8.714561995251945, 77.35743708012768,15mi","8.62482096305076, 77.34910879626493,15mi","8.732672258571409, 77.25416636022958,15mi","8.827325193109827, 77.36992950592182,15mi","8.866825338158328, 77.49568659224929,15mi","8.863096103655167, 77.78001880083059,15mi","8.910330272135548, 78.01780104606007,15mi","8.547218544130422, 77.76555056897799,15mi","8.733792681402745, 77.75296949780183,15mi","8.921321631826919, 77.38110800477975,15mi","8.980955328398414, 77.41688217223283,15mi","8.961814713810755, 77.31030496502886,15mi","9.084002753753806, 77.34011677123976,15mi","8.998622691156958, 77.8580969041542,15mi","9.002303283203481, 77.95647586465019,15mi","9.104608694349597, 78.01237300129561,15mi","8.861678190564742, 78.15174319533159,15mi","9.032482723764025, 78.24043331880902,15mi","8.863887379945904, 78.14279965346832,15mi","8.948562928231771, 77.76940678067676,15mi","9.170915054961199, 78.43456009169559,15mi","9.277183113186007, 78.13238771341081,15mi","9.396807759955918, 78.10615118954776,15mi","9.514606568626716, 78.10162765095068,15mi","9.542265574323565, 78.19028900745339,15mi","9.58954834976226, 78.30609159553859,15mi","9.447680374298512, 78.43636950713442,15mi","9.356639886723654, 78.51326966328473,15mi","9.556540312449943, 78.5811227422409,15mi","9.414658653484203, 78.35494581238703,15mi","9.447680374298512, 78.44451187660916,15mi","9.457497032470409, 77.80397881126297,15mi","9.431616148242908, 77.8229776733707,15mi","9.361103213262616, 77.91254373759284,15mi","9.311110688211112, 77.71984099335732,15mi","9.261111010371547, 77.67551031510597,15mi","9.260218094203431, 77.67008206878948,15mi","9.14769257446797, 77.69993742353019,15mi","9.177167001791677, 77.85916598214732,15mi","9.227178602772538, 77.52351941824416,15mi","9.403055677477237, 77.49818760210053,15mi","9.455712206360648, 77.5542794807043,15mi","9.519067850119514, 77.65289262212058,15mi","9.576167099592771, 77.67822443826421,15mi","9.241466330897028, 77.41404978419489,15mi","9.169128764205615, 77.39143209120951,15mi","9.266551160910847, 78.63379831600898,15mi","9.362971206194873, 78.84911875322987,15mi","9.486135638360674, 78.8916400160424,15mi","9.284408730668058, 78.98392020342278,15mi","9.238870133700718, 78.76679035076306,15mi","9.535210618017164, 78.64013127004489,15mi","9.554838635158715, 78.59127705319645,15mi","9.6208518285431, 78.71793613391462,15mi","9.635123259542945, 78.61751357705951,15mi","9.652961699573842, 78.8445952146328,15mi","9.636907146004656, 78.92782832481902,15mi","9.558407244018543, 78.80207395182026,15mi","9.629771543589996, 78.61570416162067,15mi","9.697553663405554, 78.45738031072295,15mi","9.776021101082486, 78.33434006088244,15mi","9.594983324521177, 78.30719882929998,15mi","9.540563825715077, 78.20134802612836,15mi","9.752839467237129, 79.01196614094957,15mi","9.961415753227053, 78.82016810443348,15mi","9.91685927572075, 78.81745398127521,15mi","10.077234052819039, 78.77040917986561,15mi","10.112862106425965, 78.77674213390152,15mi","10.126221608625817, 78.66727249985225,15mi","10.065654086921302, 78.55780286580297,15mi","10.030020818778477, 78.52070984930694,15mi","9.992601668588682, 78.5424228345729,15mi","10.041602061544673, 78.3325306436685,15mi","10.052292071588054, 78.08825955942632,15mi","9.941811651225482, 78.11540079100878,15mi","9.925771056751275, 78.14344673031066,15mi","9.923988719942939, 78.09006897486515,15mi","9.91240329431243, 78.11901962188644,15mi","9.927553383857378, 78.11901962188644,15mi","9.886557408714847, 78.06473715872151,15mi","9.82683673812281, 77.98693229485178,15mi","10.047837943682032, 78.08283131310982,15mi","10.090595035083687, 77.95979106326931,15mi","10.005966146365848, 77.6160020940876,15mi","9.972108403812832, 77.78880126849597,15mi","10.128893442746321, 77.5391019379373,15mi","10.005075198311113, 77.47215356670056,15mi","10.009529914139183, 77.35363685545711,15mi","10.241980588508431, 77.48572417905483,15mi","10.298954132902283, 77.35996980605607,15mi","10.448460575990824, 77.5191983646732,15mi","10.483157184574724, 77.15188702719142,15mi","10.593448707023793, 77.24235779913298,15mi","10.613012423246657, 77.3943486959948,15mi","10.463585217893709, 77.61600208725159,15mi","10.49561142853947, 77.75351766060274,15mi","10.579219764880623, 77.70194932059606,15mi","10.48582599530033, 76.96823134829096,15mi","10.527634325078592, 76.97546901004628,15mi","10.588112933089446, 76.935661870392,15mi","10.481377967931028, 77.1518870153323,15mi","10.663694409832472, 77.00622907360167,15mi","10.66636164912354, 77.03970325922005,15mi","10.66636164912354, 76.9673266416668,15mi","10.685920689003849, 77.00622907360167,15mi","10.637909892143872, 77.0080384890405,15mi","10.824575795464233, 77.01256202763759,15mi","10.749034440226987, 77.09760455326264,15mi","10.69481074533745, 77.27764138942632,15mi","10.738368251952389, 77.51829364279085,15mi","10.807691735393217, 77.0134667363012,15mi","10.960502179452268, 76.96008898085567,15mi","11.022669949744067, 76.95466073453919,15mi","11.018229829544012, 76.98903962787698,15mi","11.027998005510486, 76.90580651769075,15mi","11.043981593280828, 76.94561365734502,15mi","10.993363919024882, 76.95918427313626,15mi","11.07860971316918, 76.94199482646738,15mi","11.149628917791889, 76.9438042419062,15mi","11.107019469790155, 77.17088587947948,15mi","11.029774002644006, 77.12112695491163,15mi","10.803248401946972, 77.26768960545695,15mi","10.879664554597676, 77.19893181878136,15mi","10.997804414084095, 77.2821649289676,15mi","11.106131706717523, 77.17360000263774,15mi","11.178031748718022, 77.26045194370163,15mi","11.15406704323747, 77.44139348758472,15mi","11.174481546856432, 77.60514558479895,15mi","11.043093639001377, 77.53095955180686,15mi","11.112345991509647, 77.3581603773985,15mi","11.107019469790155, 77.3400662230102,15mi","11.126549573815423, 77.33825680757136,15mi","11.11412147713836, 77.3120202837083,15mi","11.092814936715419, 77.34368505388784,15mi","10.789918006633604, 76.65067892888098,15mi","10.82724162019218, 76.7339120390672,15mi","10.80147104960311, 76.74295911626135,15mi","10.786363134839856, 76.6696777909887,15mi","10.769476920208863, 76.65429775975863,15mi","11.236603799961985, 76.9519466050738,15mi","11.304922816702048, 76.93837598928256,15mi","11.351051129962759, 76.8008604159314,15mi","11.422889989315427, 76.85876170997399,15mi","11.351051129962759, 77.17088587317234,15mi","11.367903848106899, 77.32378147775356,15mi","11.387416276652601, 77.43053698864459,15mi","11.458359264894316, 77.43144169636402,15mi","11.43353123847623, 77.55719606936277,15mi","11.509781806486428, 77.244167198445,15mi","11.484071707720172, 77.1328881489569,15mi","11.307584270016521, 76.93566186008145,15mi","11.57448992450265, 77.58343260833293,15mi","11.588670528426045, 77.82951310801396,15mi","11.448605660644251, 77.68204574974924,15mi","11.342180881969329, 77.71823405852585,15mi","11.344841986340008, 77.74085175151124,15mi","11.476978857425033, 77.8675108322294,15mi","11.382094841326637, 77.88379557117888,15mi","11.277419713205797, 77.57981378988087,15mi","11.268547181594027, 77.40972873863075,15mi","11.670195011756585, 78.14797024900412,15mi","11.78446613770637, 78.21401391252144,15mi","11.870359656557051, 78.363290686225,15mi","11.713605893335602, 78.41304961079285,15mi","11.65247433060007, 78.40219311815986,15mi","11.664878926191468, 78.47185561255486,15mi","11.561194957936694, 78.38771779464922,15mi","11.746381021728222, 78.04392886127133,15mi","11.835828390973266, 77.93717335038029,15mi","11.828744514910312, 77.85936848651056,15mi","11.786237410052513, 77.79694365387088,15mi","11.60816768604092, 78.00321701389764,15mi","11.530170909819338, 79.11781695545145,15mi","11.678168948521526, 79.28247376038507,15mi","11.649816130344384, 79.27161726775208,15mi","11.717149337519835, 79.18747944984644,15mi","11.713605892784653, 79.32951856179467,15mi","11.743723723410657, 78.96039781227316,15mi","11.78003790631315, 78.83735756243264,15mi","11.640955281053097, 78.87535528664809,15mi","11.616143401311351, 79.49327067460692,15mi","11.56651302034496, 79.55660021496601,15mi","11.539035273086137, 79.47517652021861,15mi","11.427323896648566, 79.53217310654179,15mi","11.45126577033602, 79.65249923322405,15mi","11.749924044572255, 79.06443921560397,15mi","11.788894296166735, 78.82469166995885,15mi","11.718921042413886, 79.18657475772507,15mi","11.607281480283211, 78.60303827870206,15mi","11.593101821101273, 78.75774329872212,15mi","11.749924048326163, 79.75473122285335,15mi","11.704747085510844, 79.74749356109803,15mi","11.504462676990586, 79.73754177618446,15mi","11.447718957613231, 79.76468300776692,15mi","11.428210672558576, 79.7628735923280,15mi","11.450379074142798, 79.64797571196232,15mi","11.402493154578229, 79.69230639021367,15mi","11.419342821985742, 79.53307782049284,15mi","11.39539825267058, 79.40551403205525,15mi","11.718035190690054, 79.33766095309909,15mi","11.65158826539367, 79.26437962782641,15mi","11.683484778401189, 79.28880673625063,15mi","12.226799864136813, 79.05619100302756,15mi","12.337240926466368, 79.31627698785684,15mi","12.26005581018585, 79.42322823395486,15mi","12.404907630554272, 79.54476374088442,15mi","12.352675225772195, 79.58730116830976,15mi","12.508154483837137, 79.88749389209002,15mi","12.429833049069245, 79.82186471834805,15mi","12.377605636822071, 79.77689658078413,15mi","12.89821804443385, 80.0795200046572,15mi","13.143327867493921, 79.75623555622457,15mi","13.177647487390047, 79.60917759283979,15mi","13.122023619016213, 79.42687433244545,15mi","12.955076665852026, 79.30898489072375,15mi","12.926648973971336, 79.13032769553729,15mi","12.97876393109357, 79.13518911581447,15mi","12.907695379770066, 78.94437834101558,15mi","12.956261082147654, 78.86173419630349,15mi","12.754829695733443, 79.15220407080287,15mi","12.778535878288043, 78.72196835922497,15mi","12.633893709916002, 78.75356759102665,15mi","12.676583562063337, 78.60894033778048,15mi","12.591196727047906, 78.62473995368133,15mi","12.503408408807356, 78.57004897556301,15mi","12.555610477161904, 78.3537157732284,15mi","12.537815505201946, 78.21030387505151,15mi","12.643380960754284, 78.14589005637885,15mi","12.686069225240207, 78.0146317088949,15mi","12.754829697277577, 77.82017487436754,15mi","12.600685561559603, 77.93320289581202,15mi","12.512900480833752, 78.04380020711793,15mi","12.400159672468083, 77.99761671448469,15mi","12.533069972700394, 77.78128351215005,15mi","12.593568969354791, 77.6597480052205,15mi","12.134663125798392, 77.89446883257466,15mi","12.221387540508493, 78.05611105679098,15mi","12.122780866015011, 78.17035443330478,15mi","12.210697021650352, 78.32105846189744,15mi","12.121592610915672, 78.3866876356394,15mi","11.984908095304988, 78.25664464322476,15mi","11.917134401709031, 78.37331872987716,15mi","11.655393825066623, 78.1363244913645,15mi","12.53444196919221, 78.209560959942,15mi","12.74316503815063, 77.82532168605935,15mi","10.65122762410315, 76.99890361370818,15mi","10.074531186914939, 78.76957326901135,15mi","9.293580886876951, 79.304339257004,15mi","12.691636380103514, 78.60320158843487,15mi","11.405508530329543, 76.68200520033545,15mi","11.001392211390653, 77.75945968783135,15mi","9.840437806794217, 78.47248102527435,15mi","10.791342499094998, 79.1340063730929,15mi","10.96639423967072, 79.37960261116521,15mi","11.568461276744975, 78.65123038310918,15mi","11.445772847929414, 79.40941671350055,15mi","10.804214423641575, 77.86522070114383,15mi","10.39398580946185, 78.65818622100268,15mi","10.489754819539177, 78.13649837899027,15mi","11.915784796582825, 78.5886278420677,15mi","12.310240236060368, 79.78503195974949,15mi","11.922590665887247, 78.33126184000825,15mi","9.16769986600036, 78.11215192896556,15mi","8.426688912617934, 77.79844438934423,15mi","11.455994506402256, 79.55826717258586,15mi","12.53372283022999, 79.68834103047763,15mi","11.2159263425829, 77.9208668438306,15mi","10.697605399945276, 77.12512088966916,15mi","12.324504775874606, 77.93616965064139,15mi","13.063473275612424, 79.55826715821217,15mi","12.361877504044546, 79.97144294210369,15mi","11.830691793027682, 78.77782401086152,15mi","11.0207238158724, 77.5153424489708,15mi"]

In [ ]:
for i in range(len(Andhra_Pradesh)):
    x,y,z=Andhra_Pradesh[i].split(",")
    new=x[:9]+","+y[:9]+","+z
    Andhra_Pradesh[i]= new

In [ ]:
print(Andhra_Pradesh)

['19.048151,84.655712,15mi', '18.772602,84.459421,15mi', '18.622658, 84.23780,15mi', '18.514616, 84.06367,15mi', '18.388481, 83.90854,15mi', '18.451560, 83.55711,15mi', '18.862505, 83.39248,15mi', '18.610657, 83.32283,15mi', '18.166019, 83.37665,15mi', '17.985436, 83.41465,15mi', '18.430537, 82.89543,15mi', '18.126908, 82.68331,15mi', '18.502608, 83.09172,15mi', '17.780551, 83.22152,15mi', '17.994469, 82.90809,15mi', '18.370455, 82.42370,15mi', '17.855904, 82.51234,15mi', '17.599575, 82.62315,15mi', '17.421438, 82.54717,15mi', '17.258245, 82.33188,15mi', '17.119115, 82.30972,15mi', '17.662937, 81.72718,15mi', '17.946285, 82.05644,15mi', '16.937485, 82.21791,15mi', '16.676842, 82.19891,15mi', '17.046484, 81.81266,15mi', '16.934456, 81.80950,15mi', '16.491751, 81.99946,15mi', '16.843573, 81.50873,15mi', '16.585836, 81.52773,15mi', '16.406732, 81.78734,15mi', '16.403695, 81.45491,15mi', '16.773867, 81.06866,15mi', '16.236583, 81.10982,15mi', '16.546387, 80.63492,15mi', '15.959777, 80.99901,15mi', '16.209224, 80.67291,15mi', '16.330791, 80.43230,15mi', '16.995020, 80.73307,15mi', '16.734456, 80.42913,15mi', '16.625277, 80.03655,15mi', '16.552456, 79.71995,15mi', '16.339906, 79.47617,15mi', '16.151453, 79.20707,15mi', '16.044989, 78.95695,15mi', '15.673443, 79.27672,15mi', '15.847119, 79.81810,15mi', '15.398917, 80.03022,15mi', '15.215698, 79.90358,15mi', '15.347021, 79.51733,15mi', '15.667347, 79.26405,15mi', '15.901934, 78.64669,15mi', '15.783151, 78.23828,15mi', '15.508771, 78.47889,15mi', '15.761823, 77.62725,15mi', '15.456903, 77.84570,15mi', '15.658201, 77.26949,15mi', '15.203477, 77.32964,15mi', '14.769201, 77.56076,15mi', '14.735524, 77.74755,15mi', '14.447521, 77.71906,15mi', '14.214395, 77.77921,15mi', '14.128445, 78.13064,15mi', '14.110023, 78.75117,15mi', '14.171424, 79.19757,15mi', '14.453653, 79.47301,15mi', '15.044549, 79.16908,15mi', '13.977956, 79.98273,15mi', '13.728972, 79.76744,15mi', '13.670530, 79.39703,15mi', '13.977956, 79.33371,15mi', '13.873476, 78.95695,15mi', '13.670530, 78.77333,15mi', '13.587455, 78.49472,15mi', '13.916503, 78.16863,15mi', '14.137656, 78.17813,15mi', '14.208257, 77.77605,15mi', '14.465916, 77.68740,15mi', '13.891917, 77.50061,15mi', '14.640586, 76.85475,15mi', '14.968099, 77.02255,15mi', '15.533176, 77.12069,15mi', '13.405821, 79.75161,15mi', '13.257950, 79.10892,15mi', '12.818165, 78.41939,15mi', '14.755913, 76.94765,15mi', '17.825286, 81.87233,15mi']

In [ ]:
b="25mi"
for c in range(len(Andhra_Pradesh)):
    t=Andhra_Pradesh[c]
    temp=t[:-4]+b
    Andhra_Pradesh[c]=temp

b="25mi"
for c in range(len(Karnataka)):
    t=Karnataka[c]
    temp=t[:-4]+b
    Karnataka[c]=temp

b="25mi"
for c in range(len(Telangana)):
    t=Telangana[c]
    temp=t[:-4]+b
    Telangana[c]=temp

b="100mi"
for c in range(len(North_India)):
    t=North_India[c]
    temp=t[:-5]+b
    North_India[c]=temp
    
b="25mi"
for c in range(len(TamilNadu)):
    t=TamilNadu[c]
    temp=t[:-4]+b
    TamilNadu[c]=temp

In [ ]:
Coordinates = {"Andhra_Pradesh":Andhra_Pradesh,"Karnataka":Karnataka,"Telangana":Telangana,"North_India":North_India,"TamilNadu":TamilNadu}

In [ ]:
T_C=0
for i,j in enumerate(Coordinates):
    print(j,": ",len(Coordinates[j]))
    T_C+=len(Coordinates[j])
print("Total Coordinate:", T_C)

Andhra_Pradesh :  87
Karnataka :  205
Telangana :  154
North_India :  359
TamilNadu :  400
Total Coordinate: 1205

### Example of Twitter Data Streaming

In [ ]:
Temp_collection.delete_many({})

In [ ]:
print("Number of Documents in Collection: ",Temp_collection.estimated_document_count())

Number of Documents in Collection:  0

In [ ]:
Count = 10
Query = "Varisu"
geocode = "13.0480438,79.9288009,100mi"

In [ ]:
search_results = api.search_tweets( count=Count,q=Query, geocode=geocode)
t_count=0
for i in search_results:
    try : 
        Temp_collection.insert_one(i._json) 
        t_count+=1
        print("Tweet Saved in Collecction, Tweet_count: ",t_count)
    except : 
        print("Not Saved in collection, Tweet Id is not Unique")
        pass

Tweet Saved in Collecction, Tweet_count:  1

In [ ]:
print("Number of Documents in Collection: ",Temp_collection.estimated_document_count())

Number of Documents in Collection:  2

In [ ]:
for i in Temp_collection.find({"text":{"$regex":"Thunivu"}}).limit(10):
    try:
        print("_ _ _ _ _ _ _ _ _ _ _ ")
        print("User name:",i["user"]["name"])
        print("Text:",i["text"])
    except:
        pass

_ _ _ _ _ _ _ _ _ _ _
User name: HVinoth
Text: #Thunivu in theatres worldwide from tomorrow💥

#Ajithkumar #HVinoth
@boneykapoor @ZeeStudios_ @bayviewprojoffl… https://t.co/Z6cnxa60am
_ _ _ _ _ _ _ _ _ _ _
User name: Cinema Calendar
Text: #Thunivu in theatres worldwide from tomorrow.

#Ajithkumar #HVinoth
@boneykapoor @ZeeStudios_ @bayviewprojoffl… https://t.co/9Lk2Rr3r6j
_ _ _ _ _ _ _ _ _ _ _
User name: DK & AK
Text: #Thunivu #AjithKumar #ThunivuPongal
நாளைய தலைப்பு செய்தி;
தல அஜித்தின் துணிவு படத்தின் ஆக்ரோஷமான தாக்குதலால் துவண்… https://t.co/pYyJn76svu
_ _ _ _ _ _ _ _ _ _ _
User name: Kolly Buzz
Text: #Thunivu in theatres worldwide from tomorrow💥

#Ajithkumar #HVinoth
@boneykapoor @ZeeStudios_ @bayviewprojoffl… https://t.co/VhUraGHDU5
_ _ _ _ _ _ _ _ _ _ _
User name: DK & AK
Text: @VeeraChennaiAK #Thunivu #AjithKumar #ThunivuPongal
நாளைய தலைப்பு செய்தி;
தல அஜித்தின் துணிவு படத்தின் ஆக்ரோஷமான… https://t.co/gI5R9mxeGj
_ _ _ _ _ _ _ _ _ _ _
User name: Heytamilcinema
Text: #Thunivu in theatres worldwide from tomorrow!

#Ajithkumar #HVinoth
@boneykapoor @ZeeStudios_ @bayviewprojoffl… https://t.co/lQJPLnkVmF
_ _ _ _ _ _ _ _ _ _ _
User name: KARNATAKA AJITH FANS WELFARE ASSOCIATION
Text: @TFC_mass @UmaaRajendra 2AM Show in Bangalore 😍😍

#Thunivu #Ajithkumar
#NoGutsNoGlory
#MyThunivuTicket https://t.co/zxcbCSrD6a
_ _ _ _ _ _ _ _ _ _ _
User name: SdJose
Text: Hey @INOXMovies ,
Give few screen no. To Thunivu movie too...
U guys gave 9 shows to varisu and non to Thunivu
📍In… https://t.co/Tw4l5hNY9S
_ _ _ _ _ _ _ _ _ _ _
User name: VEERACHENNAI AJITHKUMAR WELFARE ASSOCIATION 💪
Text: ஜோதி திரையரங்கில் நம்ம அண்ணனின் படம் #Thunivu கொண்டாட்டத்திற்கு @VeeraChennaiAK ரெடி 😍😍

#Thunivu #THUNIVUFDFS https://t.co/VUq5cV8Z1c

In [ ]:
print(i.keys())

dict_keys(['_id', 'created_at', 'id', 'id_str', 'text', 'truncated', 'entities', 'extended_entities', 'metadata', 'source', 'in_reply_to_status_id', 'in_reply_to_status_id_str', 'in_reply_to_user_id', 'in_reply_to_user_id_str', 'in_reply_to_screen_name', 'user', 'geo', 'coordinates', 'place', 'contributors', 'is_quote_status', 'retweet_count', 'favorite_count', 'favorited', 'retweeted', 'possibly_sensitive', 'lang'])

### Function to Return Coordinates With Place Name:

In [ ]:
def get_coordinate(place):
    location = geolocator.geocode(place)
    return [location.latitude, location.longitude]

### Function To Add the Movie Name, Tweet_Type and Coordinates of location of Tweet

In [ ]:
tweet_count=0
for i in Temp_collection.find():
    T_count=0
    V_count=0
    try:
        # Movie Type:
        
        text = i.get('text', None)
        _id = i['id']
        V_count=text.count("varisu")+text.count("Varisu")+text.count("VARISU")
        T_count=text.count("thunivu")+text.count("Thunivu")+text.count("THUNIVU")
        if T_count>V_count:
            Temp_collection.update_one({'id': _id}, {'$set':{"movie":"Thunivu"}})
        elif V_count>T_count:
            Temp_collection.update_one({'id': _id}, {'$set':{"movie":"Varisu"}})
        elif V_count==T_count:
            Temp_collection.update_one({'id': _id}, {'$set':{"movie":"Thunivu & Varisu"}})
        else:
            Temp_collection.update_one({'id': _id}, {'$set':{"movie":None}})  
        
        # Tweet_Type analysis:
        
        blob = TextBlob(text)
        text_type=blob.sentiment.polarity
        if text_type>0:
            #positive
            Temp_collection.update_one({'id': _id}, {'$set':{"Tweet_Type":"Positive"}})
        elif text_type<0:
            #negative
            Temp_collection.update_one({'id': _id}, {'$set':{"Tweet_Type":"Negative"}})
        else:
            #neutral
            Temp_collection.update_one({'id': _id}, {'$set':{"Tweet_Type":"Neutral"}})
            
        # ADDING Coordinates to tweet with place:
        try:
            place= i.get('user', None)
            if place is not None:
                place = place.get('location', None)
            if place is not None:
                coordinate=get_coordinate(place)
                Temp_collection.update_one({'id':_id}, {'$set':{'coordinates':coordinate}})

        except:
            pass
        
    except:
        pass
    tweet_count+=1
    if tweet_count%5==0:
        print("Tweet_Count:",tweet_count)

Tweet_Count: 5
Tweet_Count: 10

In [ ]:
for i in Temp_collection.find({"movie":"Thunivu"}).limit(3):
    print("User_Name: ",i["user"]["name"],"\n""Movie: ",i["movie"],"\n","Tweet:  ",i["text"],"\n\n")

User_Name:  HVinoth
Movie:  Thunivu
 Tweet:   #Thunivu in theatres worldwide from tomorrow💥

#Ajithkumar #HVinoth
@boneykapoor @ZeeStudios_ @bayviewprojoffl… https://t.co/Z6cnxa60am


User_Name:  Cinema Calendar
Movie:  Thunivu
 Tweet:   #Thunivu in theatres worldwide from tomorrow.

#Ajithkumar #HVinoth
@boneykapoor @ZeeStudios_ @bayviewprojoffl… https://t.co/9Lk2Rr3r6j


User_Name:  DK & AK
Movie:  Thunivu
 Tweet:   #Thunivu #AjithKumar #ThunivuPongal
நாளைய தலைப்பு செய்தி;
தல அஜித்தின் துணிவு படத்தின் ஆக்ரோஷமான தாக்குதலால் துவண்… https://t.co/pYyJn76svu

In [ ]:
 print(Temp_collection.estimated_document_count())
 print(movie_TV.estimated_document_count())

NameError: ignored

In [ ]:
# pipeline = [ {"$match": {}},{"$out": "movie_TV_1"},]
# movie_TV.aggregate(pipeline)

In [ ]:
print(Temp_collection.estimated_document_count())
print(movie_TV.estimated_document_count())
print(movie_TV_1.estimated_document_count())

10
40026
40026

### Data streaming with Search Tweet API in FOR loop with more Coordinates

In [ ]:
Coordinate= Coordinates["Andhra_Pradesh"]
count=100
q_list=["varisu","thunivu"]
for q in q_list:
    for geo_i,geo in enumerate(Coordinate):   
        search_results = api.search_tweets( count=count,q=q,geocode=geo)
        tweet_count=0
        for i in search_results:
            try : 
                movie_TV.insert_one(i._json) 
                tweet_count=tweet_count+1
            except : 
                pass
        print("\n\nCoordinate:",geo_i,", tweet_count:",tweet_count,"\n")

In [ ]:
tweet_count=0
for i in movie_TV.find():
    T_count=0
    V_count=0
    try:
        text = i.get('text', None)
        _id = i['id']
        V_count=text.count("varisu")+text.count("Varisu")+text.count("VARISU")
        T_count=text.count("thunivu")+text.count("Thunivu")+text.count("THUNIVU")
        if T_count>V_count:
            movie_TV.update_one({'id': _id}, {'$set':{"movie":"Thunivu"}})
        elif V_count>T_count:
            movie_TV.update_one({'id': _id}, {'$set':{"movie":"Varisu"}})
        elif V_count==T_count:
            movie_TV.update_one({'id': _id}, {'$set':{"movie":"Thunivu & Varisu"}})
        else:
            movie_TV.update_one({'id': _id}, {'$set':{"movie":None}})  
        
        # Tweet_Type analysis:
        
        blob = TextBlob(text)
        text_type=blob.sentiment.polarity
        if text_type>0:
            #positive
            movie_TV.update_one({'id': _id}, {'$set':{"Tweet_Type":"Positive"}})
        elif text_type<0:
            #negative
            movie_TV.update_one({'id': _id}, {'$set':{"Tweet_Type":"Negative"}})
        else:
            #neutral
            movie_TV.update_one({'id': _id}, {'$set':{"Tweet_Type":"Neutral"}})
            
        # ADDING Coordinates to tweet with place:
        try:
            place= i.get('user', None)
            if place is not None:
                place = place.get('location', None)
            if place is not None:
                coordinate=get_coordinate(place)
                movie_TV.update_one({'id':_id}, {'$set':{'coordinates':coordinate}})

        except:
            pass
        
    except:
        pass
    tweet_count+=1
    if tweet_count%50==0:
        print("Tweet_Count:",tweet_count)

# Queries from movie_TV DataBase

In [ ]:
tweets = movie_TV.find({"text": {"$regex": "thunivu"}}).limit(10)
for i in tweets:
  print(i)

{'_id': ObjectId('63ba914176cfd2f2afae0ff4'), 'created_at': 'Sun Jan 08 09:15:47 +0000 2023', 'id': 1612015197287514112, 'id_str': '1612015197287514112', 'text': '@Jarus_Sk @VJViper_jd7 Varisu 10 shows thunivu 7 shows', 'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'Jarus_Sk', 'name': '𓂀 𝕊𝕦𝕣𝕒𝕛_𝕊𝕜 𓂀', 'id': 1539676850074464257, 'id_str': '1539676850074464257', 'indices': [0, 9]}, {'screen_name': 'VJViper_jd7', 'name': 'ⱽʲ VIPER ♠️', 'id': 2592490128, 'id_str': '2592490128', 'indices': [10, 22]}], 'urls': []}, 'metadata': {'iso_language_code': 'und', 'result_type': 'recent'}, 'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>', 'in_reply_to_status_id': 1611775780648005632, 'in_reply_to_status_id_str': '1611775780648005632', 'in_reply_to_user_id': 1539676850074464257, 'in_reply_to_user_id_str': '1539676850074464257', 'in_reply_to_screen_name': 'Jarus_Sk', 'user': {'id': 1226189338708303872, 'id_str': '1226189338708303872', 'name': 'Gem', 'screen_name': 'Gem36374115', 'location': 'tirunelveli', 'description': 'Tamilan 🔥', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 5, 'friends_count': 57, 'listed_count': 0, 'created_at': 'Sat Feb 08 17:01:50 +0000 2020', 'favourites_count': 84, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 93, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'F5F8FA', 'profile_background_image_url': None, 'profile_background_image_url_https': None, 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1508098294248923140/rVC0utNz_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1508098294248923140/rVC0utNz_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1226189338708303872/1648393627', 'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': True, 'has_extended_profile': True, 'default_profile': True, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none', 'withheld_in_countries': []}, 'geo': None, 'coordinates': [8.7012203, 77.5792694], 'place': None, 'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False, 'retweeted': False, 'lang': 'und', 'movie': 'Thunivu & Varisu', 'Tweet_Type': 'Neutral'}
{'_id': ObjectId('63ba914476cfd2f2afae1000'), 'created_at': 'Sun Jan 08 08:32:21 +0000 2023', 'id': 1612004266482479107, 'id_str': '1612004266482479107', 'text': '#Varisu which type promotion u admire. #VarisuTralier #VarisuFromJan11 #VarisuBooking #ThunivuBookings #thunivu… https://t.co/viwNAKBJxW', 'truncated': True, 'entities': {'hashtags': [{'text': 'Varisu', 'indices': [0, 7]}, {'text': 'VarisuTralier', 'indices': [39, 53]}, {'text': 'VarisuFromJan11', 'indices': [54, 70]}, {'text': 'VarisuBooking', 'indices': [71, 85]}, {'text': 'ThunivuBookings', 'indices': [86, 102]}, {'text': 'thunivu', 'indices': [103, 111]}], 'symbols': [], 'user_mentions': [], 'urls': [{'url': 'https://t.co/viwNAKBJxW', 'expanded_url': 'https://twitter.com/i/web/status/1612004266482479107', 'display_url': 'twitter.com/i/web/status/1…', 'indices': [113, 136]}]}, 'metadata': {'iso_language_code': 'en', 'result_type': 'recent'}, 'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>', 'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'user': {'id': 1598221927142727680, 'id_str': '1598221927142727680', 'name': 'vigyboss', 'screen_name': 'vigyboss3', 'location': 'Tirunelveli', 'description': 'Be true and Be honest.', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 2, 'friends_count': 0, 'listed_count': 0, 'created_at': 'Thu Dec 01 07:46:25 +0000 2022', 'favourites_count': 94, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 205, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'F5F8FA', 'profile_background_image_url': None, 'profile_background_image_url_https': None, 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1598223039098822656/ZF61f1t__normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1598223039098822656/ZF61f1t__normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1598221927142727680/1669881054', 'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': True, 'has_extended_profile': True, 'default_profile': True, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none', 'withheld_in_countries': []}, 'geo': None, 'coordinates': [8.7012203, 77.5792694], 'place': None, 'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False, 'retweeted': False, 'lang': 'en', 'movie': 'Varisu', 'Tweet_Type': 'Neutral'}
{'_id': ObjectId('63ba914476cfd2f2afae1003'), 'created_at': 'Sun Jan 08 08:24:26 +0000 2023', 'id': 1612002276444614658, 'id_str': '1612002276444614658', 'text': 'Back to Back FDFS Show #ThunivuFDFS #VarisuFDFS #ThalaThalapathy #ThalaThalapathyPongal @KSPSCinemas_ #thunivu… https://t.co/4GfpcKPJUC', 'truncated': True, 'entities': {'hashtags': [{'text': 'ThunivuFDFS', 'indices': [23, 35]}, {'text': 'VarisuFDFS', 'indices': [36, 47]}, {'text': 'ThalaThalapathy', 'indices': [48, 64]}, {'text': 'ThalaThalapathyPongal', 'indices': [65, 87]}, {'text': 'thunivu', 'indices': [102, 110]}], 'symbols': [], 'user_mentions': [{'screen_name': 'KSPSCinemas_', 'name': 'KSPS CINEMAS', 'id': 1177992441409880064, 'id_str': '1177992441409880064', 'indices': [88, 101]}], 'urls': [{'url': 'https://t.co/4GfpcKPJUC', 'expanded_url': 'https://twitter.com/i/web/status/1612002276444614658', 'display_url': 'twitter.com/i/web/status/1…', 'indices': [112, 135]}]}, 'metadata': {'iso_language_code': 'en', 'result_type': 'recent'}, 'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>', 'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'user': {'id': 940994504340860928, 'id_str': '940994504340860928', 'name': 'vivekanandan', 'screen_name': 'vivekanand_69', 'location': 'Thoothukkudi, India', 'description': '🎬box office collection , 🎥 Collection monitoring ,🎞️ Theatre supervising over TN ...,RAATCHASI,NKP,COMALI,SMP,ASURAN,KAITHI,HERO,MASTER,SULTHAN,KARNAN,DOCTOR', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 41, 'friends_count': 782, 'listed_count': 0, 'created_at': 'Wed Dec 13 17:19:07 +0000 2017', 'favourites_count': 1376, 'utc_offset': None, 'time_zone': None, 'geo_enabled': True, 'verified': False, 'statuses_count': 85, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'F5F8FA', 'profile_background_image_url': None, 'profile_background_image_url_https': None, 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1380950387381837826/ZZ-xnOJG_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1380950387381837826/ZZ-xnOJG_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/940994504340860928/1601791135', 'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': True, 'has_extended_profile': True, 'default_profile': True, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none', 'withheld_in_countries': []}, 'geo': None, 'coordinates': [8.756745200000001, 78.07975266019861], 'place': {'id': '562f04018a6367b1', 'url': 'https://api.twitter.com/1.1/geo/id/562f04018a6367b1.json', 'place_type': 'city', 'name': 'Thoothukkudi', 'full_name': 'Thoothukkudi, India', 'country_code': 'IN', 'country': 'India', 'contained_within': [], 'bounding_box': {'type': 'Polygon', 'coordinates': [[[77.922296, 8.65743], [78.205922, 8.65743], [78.205922, 8.851931], [77.922296, 8.851931]]]}, 'attributes': {}}, 'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False, 'retweeted': False, 'possibly_sensitive': False, 'lang': 'en', 'movie': 'Thunivu', 'Tweet_Type': 'Neutral'}
{'_id': ObjectId('63ba914776cfd2f2afae100e'), 'created_at': 'Sun Jan 08 06:28:49 +0000 2023', 'id': 1611973180536803330, 'id_str': '1611973180536803330', 'text': 'After #VarisuTralier which movie u feel? #VarisuBookings #VarisuTralier #VarisuPongal2023 #VarisuFromJan11 #varisu #thunivu #ThunivuBookings', 'truncated': False, 'entities': {'hashtags': [{'text': 'VarisuTralier', 'indices': [6, 20]}, {'text': 'VarisuBookings', 'indices': [41, 56]}, {'text': 'VarisuTralier', 'indices': [57, 71]}, {'text': 'VarisuPongal2023', 'indices': [72, 89]}, {'text': 'VarisuFromJan11', 'indices': [90, 106]}, {'text': 'varisu', 'indices': [107, 114]}, {'text': 'thunivu', 'indices': [115, 123]}, {'text': 'ThunivuBookings', 'indices': [124, 140]}], 'symbols': [], 'user_mentions': [], 'urls': []}, 'metadata': {'iso_language_code': 'en', 'result_type': 'recent'}, 'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>', 'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'user': {'id': 1598221927142727680, 'id_str': '1598221927142727680', 'name': 'vigyboss', 'screen_name': 'vigyboss3', 'location': 'Tirunelveli', 'description': 'Be true and Be honest.', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 2, 'friends_count': 0, 'listed_count': 0, 'created_at': 'Thu Dec 01 07:46:25 +0000 2022', 'favourites_count': 94, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 205, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'F5F8FA', 'profile_background_image_url': None, 'profile_background_image_url_https': None, 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1598223039098822656/ZF61f1t__normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1598223039098822656/ZF61f1t__normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1598221927142727680/1669881054', 'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': True, 'has_extended_profile': True, 'default_profile': True, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none', 'withheld_in_countries': []}, 'geo': None, 'coordinates': [8.7012203, 77.5792694], 'place': None, 'contributors': None, 'is_quote_status': False, 'retweet_count': 1, 'favorite_count': 1, 'favorited': False, 'retweeted': False, 'lang': 'en', 'movie': 'Varisu', 'Tweet_Type': 'Neutral'}
{'_id': ObjectId('63ba915b76cfd2f2afae1060'), 'created_at': 'Sun Jan 08 07:05:25 +0000 2023', 'id': 1611982389642919936, 'id_str': '1611982389642919936', 'text': '@sbcinemas Gokulam cinemas 11am show both varisu and thunivu available low price', 'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'sbcinemas', 'name': 'SB Cinemas', 'id': 915885922331144192, 'id_str': '915885922331144192', 'indices': [0, 10]}], 'urls': []}, 'metadata': {'iso_language_code': 'en', 'result_type': 'recent'}, 'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>', 'in_reply_to_status_id': 1611976966865055744, 'in_reply_to_status_id_str': '1611976966865055744', 'in_reply_to_user_id': 915885922331144192, 'in_reply_to_user_id_str': '915885922331144192', 'in_reply_to_screen_name': 'sbcinemas', 'user': {'id': 3318310975, 'id_str': '3318310975', 'name': 'Vinoth Vijay', 'screen_name': 'vino_ishere', 'location': 'Ramapuram', 'description': '', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 65, 'friends_count': 253, 'listed_count': 1, 'created_at': 'Tue Aug 18 02:48:07 +0000 2015', 'favourites_count': 140, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 334, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'C0DEED', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1511422374213652480/5mxF9b4E_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1511422374213652480/5mxF9b4E_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/3318310975/1493818902', 'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': True, 'has_extended_profile': True, 'default_profile': True, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none', 'withheld_in_countries': []}, 'geo': None, 'coordinates': [14.2012997, 78.77085116013691], 'place': None, 'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 2, 'favorited': False, 'retweeted': False, 'lang': 'en', 'movie': 'Thunivu & Varisu', 'Tweet_Type': 'Positive'}
{'_id': ObjectId('63ba916b76cfd2f2afae10a4'), 'created_at': 'Sat Jan 07 17:05:40 +0000 2023', 'id': 1611771059748978689, 'id_str': '1611771059748978689', 'text': 'Apadiye enakku oru ticket podungae yaaw 🤧🙏 #thala #thalapathy #love\n#varisu #thunivu #staysafeeveryone  #pullingow… https://t.co/myMQQn2gag', 'truncated': True, 'entities': {'hashtags': [{'text': 'thala', 'indices': [43, 49]}, {'text': 'thalapathy', 'indices': [50, 61]}, {'text': 'love', 'indices': [62, 67]}, {'text': 'varisu', 'indices': [68, 75]}, {'text': 'thunivu', 'indices': [76, 84]}, {'text': 'staysafeeveryone', 'indices': [85, 102]}, {'text': 'pullingow', 'indices': [104, 114]}], 'symbols': [], 'user_mentions': [], 'urls': [{'url': 'https://t.co/myMQQn2gag', 'expanded_url': 'https://twitter.com/i/web/status/1611771059748978689', 'display_url': 'twitter.com/i/web/status/1…', 'indices': [116, 139]}]}, 'metadata': {'iso_language_code': 'in', 'result_type': 'recent'}, 'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>', 'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'user': {'id': 1247089761375981568, 'id_str': '1247089761375981568', 'name': 'Avadi Atrocities', 'screen_name': 'AvadiAtrocities', 'location': 'Avadi', 'description': '🇦rmoured \n🇻ehicles & \n🇦mmunition \n🇩epot of\n🇮ndia\nStrictly Avadi Memes 😌', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 76, 'friends_count': 12, 'listed_count': 0, 'created_at': 'Mon Apr 06 09:12:34 +0000 2020', 'favourites_count': 127, 'utc_offset': None, 'time_zone': None, 'geo_enabled': True, 'verified': False, 'statuses_count': 232, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'F5F8FA', 'profile_background_image_url': None, 'profile_background_image_url_https': None, 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1247089893022597126/TqSZyNaQ_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1247089893022597126/TqSZyNaQ_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1247089761375981568/1589349057', 'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none', 'withheld_in_countries': []}, 'geo': None, 'coordinates': [13.1194809, 80.1026704], 'place': {'id': '07d9ef824a885003', 'url': 'https://api.twitter.com/1.1/geo/id/07d9ef824a885003.json', 'place_type': 'poi', 'name': 'Avadi', 'full_name': 'Avadi', 'country_code': 'IN', 'country': 'India', 'contained_within': [], 'bounding_box': {'type': 'Polygon', 'coordinates': [[[80.10232405358974, 13.11840507716706], [80.10232405358974, 13.11840507716706], [80.10232405358974, 13.11840507716706], [80.10232405358974, 13.11840507716706]]]}, 'attributes': {}}, 'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 2, 'favorited': False, 'retweeted': False, 'possibly_sensitive': False, 'lang': 'in', 'movie': 'Thunivu & Varisu', 'Tweet_Type': 'Positive'}

In [ ]:
data = movie_TV.find({"text": {"$regex": "thunivu"}}).limit(1)
tweet_df = pd.DataFrame(list(data))
tweet_df[:1] #display the first 10 tweets

,_id,created_at,id,id_str,text,truncated,entities,metadata,source,in_reply_to_status_id,...,place,contributors,is_quote_status,retweet_count,favorite_count,favorited,retweeted,lang,movie,Tweet_Type
0,63ba914176cfd2f2afae0ff4,Sun Jan 08 09:15:47 +0000 2023,1612015197287514112,1612015197287514112,@Jarus_Sk @VJViper_jd7 Varisu 10 shows thunivu...,False,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'iso_language_code': 'und', 'result_type': 'r...","<a href=""http://twitter.com/download/android"" ...",1611775780648005632,...,None,None,False,0,0,False,False,und,Thunivu & Varisu,Neutral

### 1.**To find all tweets that contain a specific keyword**

In [ ]:
keyword = "varisu"
tweets = movie_TV.find({"text": {"$regex": keyword}}).limit(5)
tweet_df = pd.DataFrame(list(tweets))
tweet_df[:10] #display the first 10 tweets

,_id,created_at,id,id_str,text,truncated,entities,metadata,source,in_reply_to_status_id,...,is_quote_status,retweet_count,favorite_count,favorited,retweeted,lang,movie,Tweet_Type,extended_entities,possibly_sensitive
0,63ba914076cfd2f2afae0ff0,Sun Jan 08 09:40:11 +0000 2023,1612021339371732992,1612021339371732992,@Ajith_outlook @BhuviZk @rameshlaus Avan aa po...,True,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'iso_language_code': 'et', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",1.612017e+18,...,False,0,0,False,False,et,Varisu,Neutral,NaN,NaN
1,63ba914576cfd2f2afae1007,Sun Jan 08 07:32:17 +0000 2023,1611989152790380544,1611989152790380544,@AJITH__AFC Rajini mentioned varisu .....enga ...,False,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'iso_language_code': 'et', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",1.610994e+18,...,False,0,0,False,False,et,Varisu,Neutral,NaN,NaN
2,63ba914776cfd2f2afae100e,Sun Jan 08 06:28:49 +0000 2023,1611973180536803330,1611973180536803330,After #VarisuTralier which movie u feel? #Vari...,False,"{'hashtags': [{'text': 'VarisuTralier', 'indic...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,False,1,1,False,False,en,Varisu,Neutral,NaN,NaN
3,63ba914876cfd2f2afae1014,Sun Jan 08 05:55:30 +0000 2023,1611964795259064322,1611964795259064322,Emotional edit uh 🥺❤️🫂\n@actorvijay \n\n#Varis...,False,"{'hashtags': [{'text': 'VarisuFDFS', 'indices'...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,False,3,5,False,False,en,Varisu,Neutral,"{'media': [{'id': 1611964703365906433, 'id_str...",False
4,63ba914a76cfd2f2afae101a,Sun Jan 08 05:37:16 +0000 2023,1611960206325583872,1611960206325583872,Udhay na Udhay na appdinu sombu thookkuna Thal...,False,"{'hashtags': [{'text': 'varisu', 'indices': [7...","{'iso_language_code': 'in', 'result_type': 're...","<a href=""http://twitter.com/download/iphone"" r...",NaN,...,False,0,1,False,False,in,Varisu,Neutral,NaN,NaN

### **2.	To find all tweets that were created by a specific user**

In [ ]:
username = "rameshlaus"
tweets = movie_TV.find({"user.screen_name": username},{"text":1,})
tweet_df = pd.DataFrame(list(tweets))
tweet_df[:10] #display the first 10 tweets

                        _id                                               text
0  63bab220bf318fc993cd0048  Medavakkam #Kumaran - A single screen in Cheng...
1  63bab23bbf318fc993cd00c6  Medavakkam #Kumaran - A single screen in Cheng...
2  63bab2bfbf318fc993cd01e4  Medavakkam #Kumaran - A single screen in Cheng...
3  63bab31fbf318fc993cd02ae  Medavakkam #Kumaran - A single screen in Cheng...
4  63bab426bf318fc993cd05d4  Medavakkam #Kumaran - A single screen in Cheng...
5  63bab494bf318fc993cd0698  Medavakkam #Kumaran - A single screen in Cheng...
6  63bab640bf318fc993cd0cb0  Good interview of #Thunivu Dir #HVinoth by @it...
7  63bafa98a417b0619f3fd769  #Thunivu in Kerala.. Excellent promotions by f...
8  63bafac5a417b0619f3fd835  #Thunivu in Kerala.. Excellent promotions by f...
9  63bafafca417b0619f3fd8fd  #Thunivu in Kerala.. Excellent promotions by f...

## **3.	To find all tweets that contain a specific hashtag:**

In [ ]:
tweets=movie_TV.find({"entities.hashtags.text": "varisu"})
tweet_df = pd.DataFrame(list(tweets))
tweet_df[:10] #display the first 10 tweets

,_id,created_at,id,id_str,text,truncated,entities,metadata,source,in_reply_to_status_id,...,favorited,retweeted,lang,movie,Tweet_Type,extended_entities,possibly_sensitive,quoted_status_id,quoted_status_id_str,quoted_status
0,63ba914776cfd2f2afae100e,Sun Jan 08 06:28:49 +0000 2023,1611973180536803330,1611973180536803330,After #VarisuTralier which movie u feel? #Vari...,False,"{'hashtags': [{'text': 'VarisuTralier', 'indic...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,False,False,en,Varisu,Neutral,NaN,NaN,NaN,NaN,NaN
1,63ba914876cfd2f2afae1014,Sun Jan 08 05:55:30 +0000 2023,1611964795259064322,1611964795259064322,Emotional edit uh 🥺❤️🫂\n@actorvijay \n\n#Varis...,False,"{'hashtags': [{'text': 'VarisuFDFS', 'indices'...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,False,False,en,Varisu,Neutral,"{'media': [{'id': 1611964703365906433, 'id_str...",False,NaN,NaN,NaN
2,63ba914a76cfd2f2afae101a,Sun Jan 08 05:37:16 +0000 2023,1611960206325583872,1611960206325583872,Udhay na Udhay na appdinu sombu thookkuna Thal...,False,"{'hashtags': [{'text': 'varisu', 'indices': [7...","{'iso_language_code': 'in', 'result_type': 're...","<a href=""http://twitter.com/download/iphone"" r...",NaN,...,False,False,in,Varisu,Neutral,NaN,NaN,NaN,NaN,NaN
3,63ba915976cfd2f2afae1059,Sun Jan 08 09:01:13 +0000 2023,1612011531142823937,1612011531142823937,#ThalapathyVijay dialogues then and now!😎\n#va...,False,"{'hashtags': [{'text': 'ThalapathyVijay', 'ind...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,False,False,en,Varisu,Neutral,"{'media': [{'id': 1612011448829632513, 'id_str...",False,NaN,NaN,NaN
4,63ba915d76cfd2f2afae106b,Sun Jan 08 05:37:56 +0000 2023,1611960373778984962,1611960373778984962,Meet THE Boss’s family in 3 days in theatres n...,False,"{'hashtags': [{'text': '3DaysForVarisu', 'indi...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,False,False,en,Varisu,Positive,"{'media': [{'id': 1611960358314606598, 'id_str...",False,NaN,NaN,NaN
5,63ba916676cfd2f2afae1091,Sat Jan 07 18:27:46 +0000 2023,1611791719372312576,1611791719372312576,#Gudiyatham Sakthi Cinemas opend online bookin...,False,"{'hashtags': [{'text': 'Gudiyatham', 'indices'...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,False,False,en,Thunivu & Varisu,Neutral,NaN,NaN,NaN,NaN,NaN
6,63ba916a76cfd2f2afae109f,Sat Jan 07 17:25:38 +0000 2023,1611776085641031684,1611776085641031684,Sikiram bookings open panra deeiii😭🔥 @BabuCine...,False,"{'hashtags': [{'text': 'VarisuBookings', 'indi...","{'iso_language_code': 'de', 'result_type': 're...","<a href=""http://twitter.com/download/iphone"" r...",NaN,...,False,False,de,Varisu,Neutral,"{'media': [{'id': 1611776077533417474, 'id_str...",False,NaN,NaN,NaN
7,63ba916b76cfd2f2afae10a4,Sat Jan 07 17:05:40 +0000 2023,1611771059748978689,1611771059748978689,Apadiye enakku oru ticket podungae yaaw 🤧🙏 #th...,True,"{'hashtags': [{'text': 'thala', 'indices': [43...","{'iso_language_code': 'in', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,False,False,in,Thunivu & Varisu,Positive,NaN,False,NaN,NaN,NaN
8,63ba916e76cfd2f2afae10af,Sat Jan 07 16:50:58 +0000 2023,1611767358393290753,1611767358393290753,🔥❤️‍🔥 🤣\n#varisu #Thunivu https://t.co/vmZU4Vpzsr,False,"{'hashtags': [{'text': 'varisu', 'indices': [8...","{'iso_language_code': 'und', 'result_type': 'r...","<a href=""http://twitter.com/download/android"" ...",NaN,...,False,False,und,Thunivu & Varisu,Neutral,"{'media': [{'id': 1611767267909603328, 'id_str...",False,NaN,NaN,NaN
9,63ba916f76cfd2f2afae10b5,Sat Jan 07 15:05:53 +0000 2023,1611740916443926529,1611740916443926529,#varisu Promotion In Uk🔥👌\n\n@actorvijay https...,False,"{'hashtags': [{'text': 'varisu', 'indices': [0...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,False,False,en,Varisu,Neutral,"{'media': [{'id': 1611740866670133249, 'id_str...",False,NaN,NaN,NaN

## **4.To find all tweets that have been retweeted more than a certain number of times:**

In [ ]:
tweets = movie_TV.find({"retweet_count": {"$gt": 10}}).limit(5)
tweet_df = pd.DataFrame(list(tweets))
tweet_df[:10] #display the first 10 tweets

,_id,created_at,id,id_str,text,truncated,entities,extended_entities,metadata,source,...,contributors,is_quote_status,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,lang,movie,Tweet_Type
0,63ba914876cfd2f2afae1011,Sun Jan 08 06:23:37 +0000 2023,1611971870290751490,1611971870290751490,3️⃣ DAYS TO GO 😍💥\n\n#Varisu #Thalapathy67 @ac...,False,"{'hashtags': [{'text': 'Varisu', 'indices': [1...","{'media': [{'id': 1611971866129993729, 'id_str...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",...,None,False,13,25,False,False,False,en,Varisu,Neutral
1,63ba914876cfd2f2afae1012,Sun Jan 08 06:22:57 +0000 2023,1611971700568248320,1611971700568248320,THE BOSS's Family 😍\n\n#Varisu #Thalapathy67 @...,False,"{'hashtags': [{'text': 'Varisu', 'indices': [2...","{'media': [{'id': 1611971694520045569, 'id_str...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",...,None,False,18,51,False,False,False,en,Varisu,Neutral
2,63ba914b76cfd2f2afae1021,Sun Jan 08 04:52:30 +0000 2023,1611948940038897664,1611948940038897664,This combo never disappoints us🐐✨\n#Varisu in ...,False,"{'hashtags': [{'text': 'Varisu', 'indices': [3...","{'media': [{'id': 1611948876247826432, 'id_str...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",...,None,False,14,40,False,False,False,en,Varisu,Neutral
3,63ba914c76cfd2f2afae1022,Sun Jan 08 04:51:50 +0000 2023,1611948771352662016,1611948771352662016,#Thunivu Lead in Tamil Nadu Day 1 Pre Sales wi...,False,"{'hashtags': [{'text': 'Thunivu', 'indices': [...","{'media': [{'id': 1611948762804678656, 'id_str...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",...,None,False,20,50,False,False,True,en,Thunivu,Neutral
4,63ba914f76cfd2f2afae1030,Sun Jan 08 04:06:39 +0000 2023,1611937402238676992,1611937402238676992,திருவிழா இனிதே ஆரம்பம்\n😎🔥 \n\n#ThalapathyVija...,False,"{'hashtags': [{'text': 'ThalapathyVijay', 'ind...","{'media': [{'id': 1611937309330661377, 'id_str...","{'iso_language_code': 'ta', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",...,None,False,47,124,False,False,False,ta,Varisu,Neutral

## **5.To find all tweets that are written in a specific language:**

In [ ]:
language = "en"
tweets = movie_TV.find({"lang": language}).limit(5)
tweet_df = pd.DataFrame(list(tweets))
tweet_df[:10] #display the first 10 tweets

,_id,created_at,id,id_str,text,truncated,entities,metadata,source,in_reply_to_status_id,...,is_quote_status,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,lang,movie,Tweet_Type,extended_entities
0,63ba913e76cfd2f2afae0fee,Sun Jan 08 09:40:40 +0000 2023,1612021459324633096,1612021459324633096,Now Bookings Open for Both #Thunivu &amp; #Var...,True,"{'hashtags': [{'text': 'Thunivu', 'indices': [...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",None,...,False,1,6,False,False,False,en,Thunivu & Varisu,Positive,NaN
1,63ba913f76cfd2f2afae0fef,Sun Jan 08 09:40:12 +0000 2023,1612021340546158593,1612021340546158593,Please Support my back up I'd \n@Vj_Girl2 🌼🤍\n...,False,"{'hashtags': [{'text': 'Varisu', 'indices': [4...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",None,...,False,1,3,False,False,False,en,Varisu,Neutral,"{'media': [{'id': 1612021325773803520, 'id_str..."
2,63ba914076cfd2f2afae0ff1,Sun Jan 08 09:26:29 +0000 2023,1612017891813249024,1612017891813249024,Celebrate FDFS With VMI ATTINGAL AREA COMMITTE...,True,"{'hashtags': [{'text': '3DaysForVarisu', 'indi...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",None,...,False,2,0,False,False,False,en,Varisu,Neutral,NaN
3,63ba914076cfd2f2afae0ff2,Sun Jan 08 09:22:18 +0000 2023,1612016839248449536,1612016839248449536,#Varisu AGS Booking tonight (All Properties)\n...,False,"{'hashtags': [{'text': 'Varisu', 'indices': [0...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/iphone"" r...",None,...,False,1,5,False,False,NaN,en,Varisu,Positive,NaN
4,63ba914076cfd2f2afae0ff3,Sun Jan 08 09:16:42 +0000 2023,1612015428192309249,1612015428192309249,3 Tickets available for Varisu 7:50AM Show for...,True,"{'hashtags': [{'text': 'Varisu', 'indices': [9...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/iphone"" r...",None,...,False,0,0,False,False,NaN,en,Varisu,Positive,NaN

## **6.To find all tweets that are replies to a specific user:**

In [ ]:
tweets = movie_TV.find({"in_reply_to_screen_name": "actorvijay"}).limit(5)
tweet_df = pd.DataFrame(list(tweets))
tweet_df[:10] #display the first 10 tweets

,_id,created_at,id,id_str,text,truncated,entities,metadata,source,in_reply_to_status_id,...,contributors,is_quote_status,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,lang,movie,Tweet_Type
0,63ba914376cfd2f2afae0fff,Sun Jan 08 08:33:38 +0000 2023,1612004590857388033,1612004590857388033,@actorvijay\nஇன்று\nதளபதியாரின் உத்தரவின்படி\n...,True,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'iso_language_code': 'ta', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",None,...,None,False,1,8,False,False,False,ta,Thunivu & Varisu,Neutral
1,63baaf02bf318fc993ccf76b,Sun Jan 08 11:53:56 +0000 2023,1612054996463529984,1612054996463529984,@actorvijay 's #Varisu \n@\n#AjithKumar 's #Th...,True,"{'hashtags': [{'text': 'Varisu', 'indices': [1...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""https://mobile.twitter.com"" rel=""nofo...",None,...,None,False,1,6,False,False,False,en,Thunivu & Varisu,Neutral
2,63baaf18bf318fc993ccf7cf,Sun Jan 08 11:53:56 +0000 2023,1612054996463529984,1612054996463529984,@actorvijay 's #Varisu \n@\n#AjithKumar 's #Th...,True,"{'hashtags': [{'text': 'Varisu', 'indices': [1...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""https://mobile.twitter.com"" rel=""nofo...",None,...,None,False,1,6,False,False,False,en,NaN,NaN
3,63baafb4bf318fc993ccf958,Sun Jan 08 08:33:38 +0000 2023,1612004590857388033,1612004590857388033,@actorvijay\nஇன்று\nதளபதியாரின் உத்தரவின்படி\n...,True,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'iso_language_code': 'ta', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",None,...,None,False,2,9,False,False,False,ta,NaN,NaN
4,63bab005bf318fc993ccf9fc,Sun Jan 08 08:33:38 +0000 2023,1612004590857388033,1612004590857388033,@actorvijay\nஇன்று\nதளபதியாரின் உத்தரவின்படி\n...,True,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'iso_language_code': 'ta', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",None,...,None,False,2,9,False,False,False,ta,NaN,NaN

## **7.To find all tweets that contain a specific URL:**

In [ ]:
tweets = movie_TV.find({"entities.urls.expanded_url": "https://www.youtube.com/watch?v=9fux9swQ5AQ"})
tweet_df = pd.DataFrame(list(tweets))
tweet_df[:10] #display the first 10 tweets

,_id,created_at,id,id_str,text,truncated,entities,metadata,source,in_reply_to_status_id,...,contributors,is_quote_status,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,lang,movie,Tweet_Type
0,63baf88fa417b0619f3fd0e4,Wed Jan 04 11:37:51 +0000 2023,1610601397829111809,1610601397829111809,https://t.co/MEkudkEPJP\nHere is #VarisuTralie...,True,"{'hashtags': [{'text': 'VarisuTralier', 'indic...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""https://mobile.twitter.com"" rel=""nofo...",None,...,None,False,0,0,False,False,False,en,Varisu,Positive

## **8.To find all tweets that are marked as sensitive content:**

In [ ]:
tweets = movie_TV.find({"user.verified": True}).limit(5)
tweet_df = pd.DataFrame(list(tweets))
tweet_df[:10] #display the first 10 tweets

,_id,created_at,id,id_str,text,truncated,entities,metadata,source,in_reply_to_status_id,...,is_quote_status,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,lang,movie,Tweet_Type,extended_entities
0,63ba915276cfd2f2afae103e,Sun Jan 08 03:37:31 +0000 2023,1611930069035020288,1611930069035020288,Online bookings for all #Varisu &amp; #Thunivu...,True,"{'hashtags': [{'text': 'Varisu', 'indices': [2...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",None,...,False,703,3626,False,False,False,en,Thunivu & Varisu,Neutral,NaN
1,63baa1f376cfd2f2afae110e,Sun Jan 08 03:37:31 +0000 2023,1611930069035020288,1611930069035020288,Online bookings for all #Varisu &amp; #Thunivu...,True,"{'hashtags': [{'text': 'Varisu', 'indices': [2...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",None,...,False,724,3842,False,False,False,en,NaN,NaN,NaN
2,63baa1f476cfd2f2afae1112,Sun Jan 08 03:06:29 +0000 2023,1611922261778501633,1611922261778501633,Bookings for AK's #Thunivu FDFS will begin by ...,True,"{'hashtags': [{'text': 'Thunivu', 'indices': [...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",None,...,False,613,2149,False,False,False,en,Thunivu,Neutral,NaN
3,63baaa45f242a98cabfe4f05,Sun Jan 08 11:30:30 +0000 2023,1612049101444497408,1612049101444497408,"அங்க இருந்த Vibe-ல பேசிட்டேன்., - #ViralTwins ...",True,"{'hashtags': [{'text': 'ViralTwins', 'indices'...","{'iso_language_code': 'und', 'result_type': 'r...","<a href=""https://mobile.twitter.com"" rel=""nofo...",None,...,False,0,9,False,False,False,und,Thunivu & Varisu,Neutral,NaN
4,63baaa45f242a98cabfe4f06,Sun Jan 08 11:30:05 +0000 2023,1612048994443874305,1612048994443874305,"எங்களுக்கு Fans தான் பயம், மத்தபடி! - THEATRE ...",False,"{'hashtags': [{'text': 'varisu', 'indices': [8...","{'iso_language_code': 'et', 'result_type': 're...","<a href=""https://mobile.twitter.com"" rel=""nofo...",None,...,False,1,5,False,False,False,et,Thunivu & Varisu,Negative,"{'media': [{'id': 1612048823555346432, 'id_str..."

## **9.To find all tweets that are from a verified user:**

In [ ]:
tweets = movie_TV.find({"user.verified": True}).limit(5)
tweet_df = pd.DataFrame(list(tweets))
tweet_df[:10] #display the first 10 tweets

,_id,created_at,id,id_str,text,truncated,entities,metadata,source,in_reply_to_status_id,...,is_quote_status,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,lang,movie,Tweet_Type,extended_entities
0,63ba915276cfd2f2afae103e,Sun Jan 08 03:37:31 +0000 2023,1611930069035020288,1611930069035020288,Online bookings for all #Varisu &amp; #Thunivu...,True,"{'hashtags': [{'text': 'Varisu', 'indices': [2...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",None,...,False,703,3626,False,False,False,en,Thunivu & Varisu,Neutral,NaN
1,63baa1f376cfd2f2afae110e,Sun Jan 08 03:37:31 +0000 2023,1611930069035020288,1611930069035020288,Online bookings for all #Varisu &amp; #Thunivu...,True,"{'hashtags': [{'text': 'Varisu', 'indices': [2...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",None,...,False,724,3842,False,False,False,en,NaN,NaN,NaN
2,63baa1f476cfd2f2afae1112,Sun Jan 08 03:06:29 +0000 2023,1611922261778501633,1611922261778501633,Bookings for AK's #Thunivu FDFS will begin by ...,True,"{'hashtags': [{'text': 'Thunivu', 'indices': [...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",None,...,False,613,2149,False,False,False,en,Thunivu,Neutral,NaN
3,63baaa45f242a98cabfe4f05,Sun Jan 08 11:30:30 +0000 2023,1612049101444497408,1612049101444497408,"அங்க இருந்த Vibe-ல பேசிட்டேன்., - #ViralTwins ...",True,"{'hashtags': [{'text': 'ViralTwins', 'indices'...","{'iso_language_code': 'und', 'result_type': 'r...","<a href=""https://mobile.twitter.com"" rel=""nofo...",None,...,False,0,9,False,False,False,und,Thunivu & Varisu,Neutral,NaN
4,63baaa45f242a98cabfe4f06,Sun Jan 08 11:30:05 +0000 2023,1612048994443874305,1612048994443874305,"எங்களுக்கு Fans தான் பயம், மத்தபடி! - THEATRE ...",False,"{'hashtags': [{'text': 'varisu', 'indices': [8...","{'iso_language_code': 'et', 'result_type': 're...","<a href=""https://mobile.twitter.com"" rel=""nofo...",None,...,False,1,5,False,False,False,et,Thunivu & Varisu,Negative,"{'media': [{'id': 1612048823555346432, 'id_str..."

## **10.To find all tweets that have been sent from a specific location**:

In [ ]:
tweets = movie_TV.find({"user.location": "Chennai"}).limit(5)
tweet_df = pd.DataFrame(list(tweets))
tweet_df[:10] #display the first 10 tweets

,_id,created_at,id,id_str,text,truncated,entities,metadata,source,in_reply_to_status_id,...,is_quote_status,retweet_count,favorite_count,favorited,retweeted,lang,movie,Tweet_Type,extended_entities,possibly_sensitive
0,63ba915b76cfd2f2afae105f,Sun Jan 08 07:20:44 +0000 2023,1611986244753584130,1611986244753584130,Thunivu &amp; Varisu FDFS in my @rakkicinemas 🥰😇,False,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'iso_language_code': 'und', 'result_type': 'r...","<a href=""http://twitter.com/download/iphone"" r...",None,...,False,9,35,False,False,und,Thunivu & Varisu,Neutral,NaN,NaN
1,63ba916676cfd2f2afae108e,Sat Jan 07 18:41:12 +0000 2023,1611795100962807809,1611795100962807809,AJITH MAFIA #BEAST #VARISU #Thalapathy67𓃵 #Var...,False,"{'hashtags': [{'text': 'BEAST', 'indices': [12...","{'iso_language_code': 'und', 'result_type': 'r...","<a href=""http://twitter.com/download/iphone"" r...",None,...,False,0,0,False,False,und,Varisu,Neutral,"{'media': [{'id': 1611795086580551680, 'id_str...",False
2,63baa1fc76cfd2f2afae1131,Sun Jan 08 07:20:44 +0000 2023,1611986244753584130,1611986244753584130,Thunivu &amp; Varisu FDFS in my @rakkicinemas 🥰😇,False,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'iso_language_code': 'und', 'result_type': 'r...","<a href=""http://twitter.com/download/iphone"" r...",None,...,False,9,36,False,False,und,NaN,NaN,NaN,NaN
3,63baaa45f242a98cabfe4f05,Sun Jan 08 11:30:30 +0000 2023,1612049101444497408,1612049101444497408,"அங்க இருந்த Vibe-ல பேசிட்டேன்., - #ViralTwins ...",True,"{'hashtags': [{'text': 'ViralTwins', 'indices'...","{'iso_language_code': 'und', 'result_type': 'r...","<a href=""https://mobile.twitter.com"" rel=""nofo...",None,...,False,0,9,False,False,und,Thunivu & Varisu,Neutral,NaN,False
4,63baaa45f242a98cabfe4f06,Sun Jan 08 11:30:05 +0000 2023,1612048994443874305,1612048994443874305,"எங்களுக்கு Fans தான் பயம், மத்தபடி! - THEATRE ...",False,"{'hashtags': [{'text': 'varisu', 'indices': [8...","{'iso_language_code': 'et', 'result_type': 're...","<a href=""https://mobile.twitter.com"" rel=""nofo...",None,...,False,1,5,False,False,et,Thunivu & Varisu,Negative,"{'media': [{'id': 1612048823555346432, 'id_str...",False

In [ ]:
tweets = movie_TV.find({"user.location": "Hyderabad"}).limit(5)
tweet_df = pd.DataFrame(list(tweets))
tweet_df[:10] #display the first 10 tweets

,_id,created_at,id,id_str,text,truncated,entities,metadata,source,in_reply_to_status_id,...,contributors,is_quote_status,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,lang,movie,Tweet_Type
0,63bab81cbf318fc993cd1186,Sun Jan 08 11:41:31 +0000 2023,1612051871450947585,1612051871450947585,Meet THE BOSS’s family in 3 days in theatres n...,True,"{'hashtags': [{'text': '3DaysForVarisu', 'indi...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""https://www.hootsuite.com"" rel=""nofol...",NaN,...,None,False,0,0,False,False,False,en,Varisu,Positive
1,63bab81dbf318fc993cd1188,Sun Jan 08 11:21:16 +0000 2023,1612046774549753856,1612046774549753856,#ThunivuBookings\n#Thunivu on 11th\n#VeeraSimh...,True,"{'hashtags': [{'text': 'ThunivuBookings', 'ind...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,None,False,0,1,False,False,NaN,en,Thunivu,Neutral
2,63bab821bf318fc993cd119b,Sun Jan 08 08:01:46 +0000 2023,1611996570194673664,1611996570194673664,Interesting: Varisu censored with zero cuts\n\...,True,"{'hashtags': [{'text': '123telugu', 'indices':...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""https://about.twitter.com/products/tw...",NaN,...,None,False,0,10,False,False,False,en,Varisu,Positive
3,63bab821bf318fc993cd119d,Sun Jan 08 07:43:07 +0000 2023,1611991877099876352,1611991877099876352,"@Suryasubramany1 11th #Varisu ki Sudarshan, Sa...",True,"{'hashtags': [{'text': 'Varisu', 'indices': [2...","{'iso_language_code': 'hi', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",1.611991e+18,...,None,False,0,0,False,False,NaN,hi,Varisu,Neutral
4,63bab822bf318fc993cd11a0,Sun Jan 08 07:27:41 +0000 2023,1611987993727832065,1611987993727832065,Advance Booking for Day1 #Pongal2023 \n\nTamil...,True,"{'hashtags': [{'text': 'Pongal2023', 'indices'...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""https://mobile.twitter.com"" rel=""nofo...",NaN,...,None,False,220,413,False,False,NaN,en,Thunivu & Varisu,Neutral

## **11.To find the most popular hashtags used in tweets about a specific movie:**

In [ ]:
pipeline = [
    {"$match": {"text": {"$regex": "varisu"}}},
    {"$unwind": "$entities.hashtags"},
    {"$group": {"_id": "$entities.hashtags.text", "count": {"$sum": 1}}},
    {"$sort": {"count": -1}},
    {"$limit": 5}
]
result = movie_TV.aggregate(pipeline)
tweet_df = pd.DataFrame(list(result))
tweet_df[:10] #display the first 10 tweets

               _id  count
0           varisu   1430
1          thunivu    592
2          Thunivu    269
3           Varisu    112
4  VeeraSimhaReddy    105

In [ ]:
pipeline = [
    {"$match": {"text": {"$regex": "thunivu"}}},
    {"$unwind": "$entities.hashtags"},
    {"$group": {"_id": "$entities.hashtags.text", "count": {"$sum": 1}}},
    {"$sort": {"count": -1}},
    {"$limit": 5}
]
result = movie_TV.aggregate(pipeline)
tweet_df = pd.DataFrame(list(result))
tweet_df[:10] #display the first 10 tweets

        _id  count
0   thunivu    916
1    varisu    609
2  anthanan    102
3   dilraju     96
4    Varisu     77

## **12.To find the most common words used in tweets about a specific movie:**

In [ ]:
pipeline = [
    {"$match": {"text": {"$regex": "Varisu"}}},
    {"$project": {"words": {"$split": ["$text", " "]}}},
    {"$unwind": "$words"},
    {"$group": {"_id": "$words", "count": {"$sum": 1}}},
    {"$sort": {"count": -1}},
    {"$limit": 5}
]
result = movie_TV.aggregate(pipeline)
tweet_df = pd.DataFrame(list(result))
tweet_df[:10] #display the first 10 tweets

       _id  count
0  #Varisu   8200
1       in   4533
2        -   4105
3            3858
4   Varisu   2945

## **13.Who are the most active users (by number of tweets) who tweeted about a specific movie?**

In [ ]:
pipeline = [
    {"$match": {"text": {"$regex": "Varisu"}}},
    {"$group": {"_id": "$user.screen_name", "count": {"$sum": 1}}},
    {"$sort": {"count": -1}},
    {"$limit": 5}
]
result = movie_TV.aggregate(pipeline)
tweet_df = pd.DataFrame(list(result))
tweet_df[:10] #display the first 10 tweets

               _id  count
0    Nandu_4EverPK    451
1    withPKwithJSP    430
2  PrintingMateri2    391
3   DelhiBollywood    390
4      Dhoni_Varsh    340

### 14). To create a recommendation system that suggests similar tweets about a specific movie based on their text:

In [ ]:
# First, create the feature matrix

from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import CountVectorizer
import sklearn

data = movie_TV.find({"text": {"$regex": "Varisu"}}).limit(500)
X = []
for tweet in data:
    X.append(tweet["text"])

# Then, use a count vectorizer to convert the text into numerical features
vectorizer = CountVectorizer()
X_features = vectorizer.fit_transform(X)

# Next, use cosine similarity to compute similarity scores between all pairs of tweets
similarity = sklearn.metrics.pairwise.cosine_similarity(X_features)

# Finally, for a given tweet, find the indices of the most similar tweets
tweet_index =1611918228258971648 # specify the index of the tweet for which you want to find similar tweets
documesnt = movie_TV.find_one({"id": tweet_index})
document_index = list(movie_TV.find().limit(500)).index(documesnt)
print(document_index)
similar_indices = similarity[document_index].argsort()[::-1][1:]  # exclude the tweet itself
similar_tweets = [X[i] for i in similar_indices]
tweet_taken=movie_TV.find_one({"id": tweet_index},{'text':1,'_id':0})
print("Similar tweets:", {tweet_taken['text']:similar_tweets})

89

In [ ]:
# Iterating over documents in the temporary collection to add movie names, tweet types, and coordinates
for i in Temp_collection.find():
    try:
        text = i.get('text', None)
        _id = i['id']

        # Movie Type analysis
        V_count = text.count("varisu") + text.count("Varisu") + text.count("VARISU")
        T_count = text.count("thunivu") + text.count("Thunivu") + text.count("THUNIVU")
        if T_count > V_count:
            Temp_collection.update_one({'id': _id}, {'$set': {"movie": "Thunivu"}})
        elif V_count > T_count:
            Temp_collection.update_one({'id': _id}, {'$set': {"movie": "Varisu"}})
        elif V_count == T_count:
            Temp_collection.update_one({'id': _id}, {'$set': {"movie": "Thunivu & Varisu"}})
        else:
            Temp_collection.update_one({'id': _id}, {'$set': {"movie": None}})

        # Tweet_Type analysis
        blob = TextBlob(text)
        text_type = blob.sentiment.polarity
        if text_type > 0:
            Temp_collection.update_one({'id': _id}, {'$set': {"Tweet_Type": "Positive"}})
        elif text_type < 0:
            Temp_collection.update_one({'id': _id}, {'$set': {"Tweet_Type": "Negative"}})
        else:
            Temp_collection.update_one({'id': _id}, {'$set': {"Tweet_Type": "Neutral"}})

        # Adding Coordinates to tweet with place
        place = i.get('user', None)
        if place is not None:
            place = place.get('location', None)
        if place is not None:
            coordinate = get_coordinate(place)
            Temp_collection.update_one({'id': _id}, {'$set': {'coordinates': coordinate}})

    except:
        pass